from pathlib import Path
import json,re
ROOT=Path(__file__).resolve().parent.parent
SRC=ROOT/'_source'
NAMES=['login','home','tema','focus','feedback','perfil']
TITLES=['Entrar','Escolher assunto','Seu tema','Focus','Explicação e feedback','Perfil e evolução']
ICONS={
'leaf':'<path d="M20 4C9 2 3 6 5 14c2 6 12 5 15-10Z"/><path d="m4 21 12-12M8 17l-1-6m5 2 5 1"/>',
'arrow':'<path d="M4 12h15m-6-6 6 6-6 6"/>',
'back':'<path d="M20 12H5m6-6-6 6 6 6"/>',
'book':'<path d="M3 4h6l3 2 3-2h6v15h-6l-3 2-3-2H3ZM12 6v15"/>',
'home':'<path d="m3 11 9-8 9 8M5 9v12h14V9M9 21v-8h6v8"/>',
'clock':'<circle cx="12" cy="12" r="9"/><path d="M12 7v6l4 2"/>',
'score':'<path d="M4 20h16M6 16v-4m6 4V5m6 11V9"/>',
'person':'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',
'check':'<path d="m5 12 4 4L19 6"/>',
'search':'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',
'shuffle':'<path d="M3 5h3l12 14h3m-5-4 4 4-4 3M3 19h3l4-5m4-4 4-5h3m-5-3 4 3-4 4"/>',
'mic':'<rect x="9" y="2" width="6" height="13" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3m-4 0h8"/>',
'upload':'<path d="M12 16V3m-5 5 5-5 5 5M4 16v5h16v-5"/>',
'mail':'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',
'lock':'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4M12 15v2"/>',
'info':'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-11v2"/>',
'atom':'<ellipse cx="12" cy="12" rx="10" ry="4"/><ellipse cx="12" cy="12" rx="10" ry="4" transform="rotate(60 12 12)"/><ellipse cx="12" cy="12" rx="10" ry="4" transform="rotate(120 12 12)"/>',
'sun':'<circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/>',
'logout':'<path d="M10 3H4v18h6m-1-9h12m-4-4 4 4-4 4"/>',
'alert':'<path d="m12 3 10 18H2ZM12 9v5m0 2v2"/>',
'headphones':'<path d="M3 16v-5a9 9 0 0 1 18 0v5M3 12h4v9H3Zm14 0h4v9h-4Z"/>',
'chevron':'<path d="m9 5 7 7-7 7"/>',
'volume':'<path d="M3 9h4l5-5v16l-5-5H3ZM16 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>'}
def ic(name,small=False):return f'<svg class="icon{" sm" if small else ""}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{ICONS[name]}</svg>'
def href(page):return f'{page+1:02d}-{NAMES[page]}.html'
def link(label,page,kind='primary',extra=''):return f'<a class="btn {kind}" href="{href(page)}" {extra}>{label}</a>'
def btn(label,action,kind='primary',extra=''):return f'<button type="button" class="btn {kind}" data-action="{action}" {extra}>{label}</button>'
def badge(label,kind=''):return f'<span class="badge {kind}">{label}</span>'
def logo():return f'<a class="logo" href="{href(1)}" aria-label="JustStudy, início"><span class="logomark">{ic("book",True)}</span>juststudy<span class="accent">.</span></a>'
def steps(step):
    names=['Escolher','Focar','Explicar']
    return '<nav class="steps" aria-label="Etapas do estudo">'+ '<span class="connector" aria-hidden="true"></span>'.join(f'<span class="step {"active" if i==step else ""}"><span class="step-index">{ic("check",True) if i<step else i+1}</span>{n}</span>' for i,n in enumerate(names))+'</nav>'
def art():
    return '''<svg class="botanical" viewBox="0 0 400 360" fill="none" aria-label="Ilustração de uma planta captando a luz do sol" role="img"><circle cx="300" cy="75" r="30" stroke="currentColor" stroke-width="1" opacity=".45"/><g stroke="currentColor" stroke-width="1.3" opacity=".45"><path d="M300 28V12M300 120v14M347 75h16M254 75h-16M332 43l12-12M267 108l-12 12M332 108l12 12M267 43l-12-12"/></g><path d="M202 301c-6-55-20-105-6-158" stroke="currentColor" stroke-width="2"/><path d="M195 203c-56 1-91-37-90-83 62-5 99 29 90 83Z" fill="currentColor" fill-opacity=".11" stroke="currentColor" stroke-width="1.6"/><path d="M195 203c-20-25-48-51-90-83M164 168l2-31M165 169l-38-5" stroke="currentColor" stroke-width="1.1"/><path d="M198 160c-21-42-7-86 29-112 27 47 24 92-29 112Z" fill="currentColor" fill-opacity=".06" stroke="currentColor" stroke-width="1.6"/><path d="M198 160c14-40 22-75 29-112M210 119l-15-23M211 114l24-20" stroke="currentColor" stroke-width="1.1"/><path d="M198 250c54-2 91-37 97-86-63-3-102 34-97 86Z" fill="currentColor" fill-opacity=".18" stroke="currentColor" stroke-width="1.6"/><path d="M198 250c27-37 57-66 97-86M234 209l6-30M234 209l36-5M173 310h57M181 319h40" stroke="currentColor" stroke-width="1.1"/><path d="M76 287h47M100 273v28" stroke="currentColor" opacity=".3"/><circle cx="313" cy="274" r="4" fill="currentColor" opacity=".3"/></svg>'''
def footer():return '<footer class="footer"><span>JUSTSTUDY · UM ASSUNTO DE CADA VEZ</span><span>Escolha. Explore. Explique.</span></footer>'
def chrome(v,p,content):
    side=''
    if v=='estudio' and p!=0:
        side=f'''<aside class="sidebar">{logo()}<div><div class="eyebrow">Seu espaço</div><nav class="side-nav"><a href="{href(1)}" {'aria-current="page"' if p in [1,2] else ''}>{ic('home')}Visão geral</a><a href="{href(3)}" {'aria-current="page"' if p==3 else ''}>{ic('clock')}Sessão de foco</a><a href="{href(4)}" {'aria-current="page"' if p==4 else ''}>{ic('mic')}Feedback</a><a href="{href(5)}" {'aria-current="page"' if p==5 else ''}>{ic('score')}Minha evolução</a></nav></div><div class="sidebar-plan"><div class="row between"><strong>Plano Student</strong>{ic('check',True)}</div><p>875 de 1.000 créditos disponíveis</p><div class="progress mt" style="background:#42506a"><span style="width:87.5%;background:#9eb6ff"></span></div><a href="{href(5)}#account" class="text-link" style="color:#b9ccff;margin-top:12px">Gerenciar plano {ic('arrow',True)}</a></div><a href="{href(5)}" class="row"><span class="avatar">DS</span><div><div style="color:#fff;font-size:12px">Daniel Silva</div><span style="font-size:10px">Seu perfil {ic('chevron',True)}</span></div></a></aside>'''
    top=f'''<header class="topbar">{logo()}{'<span class="eyebrow">Seu espaço de estudo / '+TITLES[p]+'</span>' if v=='estudio' and p else ''}<nav class="top-links" aria-label="Navegação principal">{f'<a href="{href(1)}" '+('aria-current="page"' if p in [1,2,3,4] else '')+'>Estudar</a>' if p else '<span class="small muted">Aprender começa com curiosidade.</span>'}{f'<a href="{href(5)}" '+('aria-current="page"' if p==5 else '')+'>Minha evolução</a><a class="avatar" href="'+href(5)+'" aria-label="Abrir perfil">DS</a>' if p else ''}</nav></header>'''
    return side+top+f'<main class="page" id="main">{content}</main>'+footer()
def login(v):
    copy={'ritual':('Menos distração.<br>Mais descoberta.','Um tema, um tempo para focar e uma explicação com as suas palavras.'),'estudio':('Seu conhecimento.<br>Em construção.','Escolha um assunto, estude com intenção e descubra o que você realmente entendeu.'),'caderno':('Aprender é<br>deixar a curiosidade<br><em class="accent">entrar.</em>','Abra espaço para uma nova ideia. Um assunto por vez, no seu ritmo.')}[v]
    form=f'''<form class="login-form stack" data-form="login"><button type="button" class="btn secondary full" data-action="google"><span style="font-weight:700;font-size:18px;color:#4285f4">G</span> Continuar com Google</button><div class="divider">ou entre com seu e-mail</div><div class="field"><label for="email">Seu e-mail</label><input class="input" id="email" name="email" type="email" placeholder="voce@exemplo.com" required autocomplete="email"></div><button class="btn primary full" type="submit">Receber link de acesso {ic('arrow',True)}</button><p class="small center">Sem senha. Um link para você entrar.</p><button type="button" class="text-link" style="align-self:center" data-action="guest">Explorar como visitante {ic('arrow',True)}</button></form>'''
    visual=f'''<div class="login-visual" role="img" aria-label="Uma prévia da sua jornada"><div class="card"><div class="row between"><span class="eyebrow">Uma ideia para hoje</span>{ic('leaf')}</div>{art()}<div class="row between"><div><h3>Fotossíntese</h3><p class="small">Biologia · 25 minutos de foco</p></div>{ic('arrow')}</div></div><div class="mini-score"><div class="row">{ic('mic')}<div><strong style="font-size:12px">Aprendeu? Conte com suas palavras.</strong><p style="font-size:10px">Sua explicação vira um caminho de revisão.</p></div></div></div><p class="login-note">01 Escolher &nbsp; / &nbsp; 02 Focar &nbsp; / &nbsp; 03 Explicar</p></div>'''
    return f'<div class="login-grid"><section class="login-copy"><div class="eyebrow mb">{ "Seu próximo capítulo" if v=="caderno" else "Um espaço para aprender de verdade"}</div><h1>{copy[0]}</h1><p>{copy[1]}</p>{form}</section>{visual}</div><section class="card" id="login-sent" hidden aria-live="polite"><div class="record-icon">{ic("mail")}</div><h2 class="center mt">Confira seu e-mail</h2><p class="center mt">Enviamos um link para <strong data-email>voce@exemplo.com</strong>.</p><div class="row mt" style="justify-content:center">{btn("Enviar novamente","resend","secondary")}{btn("Abrir acesso de exemplo "+ic("arrow",True),"login")}</div><p class="small center mt">Demonstração local: nenhum e-mail é enviado.</p></section>'
SUBJECTS=[('biology','Biologia','leaf','',214,'3 temas avaliados'),('mathematics','Matemática','math','ochre',342,'4 temas avaliados'),('physics','Física','atom','blue',180,'1 tema avaliado')]
def subjects(v):
    cards=[]
    for i,(slug,name,symbol,tone,score,desc) in enumerate(SUBJECTS):
        mark=str(i+1).zfill(2) if v=='caderno' else ('∑' if symbol=='math' else ic(symbol))
        cards.append(f'''<button type="button" class="subject-card" data-subject="{slug}" aria-pressed="{'true' if i==0 else 'false'}"><span class="selection" aria-hidden="true"></span><span class="subject-symbol {tone}">{mark}</span><div class="grow"><h3>{name}</h3><p class="small">100 temas para explorar</p><p class="small" style="margin-top:6px">15 iniciais · 35 intermediários<br>30 avançados · 20 especialistas</p></div><div class="subject-bottom"><div><strong>{score}</strong><small> / 1.000</small></div><small>{desc}</small></div><div class="progress"><span style="width:{score/10}%"></span></div></button>''')
    return '<div class="subject-grid" id="subjects">'+''.join(cards)+'</div><p id="no-results" class="empty-search muted" hidden>Nenhum assunto encontrado. Tente outro nome.</p>'
def home(v):
    title={'ritual':'O que vamos descobrir hoje?','estudio':'Bom dia, Daniel.','caderno':'Qual será a descoberta de hoje?'}[v]
    heading=f'<div class="page-title"><div><div class="eyebrow mb">{ "Página 01 / a escolha" if v=="caderno" else "Seu próximo estudo"}</div><h1>{title}</h1><p>Escolha o assunto. A gente encontra seu próximo tema.</p></div>{steps(0) if v=="ritual" else badge("Student · 875 créditos","neutral")}</div>'
    search=f'<div class="row between mb"><h3>{"Seus assuntos" if v=="estudio" else "Um ponto de partida"}</h3><div class="search" style="max-width:220px">{ic("search")}<input type="search" class="input" id="subject-search" aria-label="Buscar assunto" placeholder="Buscar assunto"></div></div>'
    bar=f'<div class="choose-bar"><div class="row">{ic("shuffle")}<div><strong class="small"><span data-subject-name>Biologia</span> selecionada</strong><p class="small">O tema aparece depois do sorteio.</p></div></div>{btn("Sortear meu tema "+ic("arrow",True),"randomize")}</div><div class="center">{btn("Surpreenda-me com qualquer assunto","surprise","ghost")}</div>'
    aside=f'''<aside class="{'editorial-aside' if v=='caderno' else 'stack'}">{'<span class="chapter">01.</span>' if v=='caderno' else ''}<div class="{'editorial-note' if v=='caderno' else 'card'}"><div class="eyebrow">Como funciona</div><h3 style="margin:14px 0">Uma ideia merece atenção.</h3><p class="small">O tema é uma surpresa. Você escolhe o tempo, estuda e depois explica o que entendeu.</p><hr class="rule"><div class="stack"><div class="journey-note">{ic('book')}<div><strong class="small">Explore no seu material</strong><p class="small">Livro, aula ou uma boa referência.</p></div></div><div class="journey-note">{ic('mic')}<div><strong class="small">Aprenda ao explicar</strong><p class="small">Receba correções e próximos passos.</p></div></div></div></div><div class="{'editorial-note' if v=='caderno' else 'card soft'}"><div class="eyebrow">Última descoberta</div><h3 style="margin:12px 0 5px">Estrutura celular</h3><p class="small">Biologia · ontem</p><a class="text-link mt" href="{href(5)}#history">Abrir meu histórico {ic('arrow',True)}</a></div></aside>'''
    summary=f'<div class="stats mb"><div class="card"><p class="eyebrow">Assuntos explorados</p><div class="stat-value mt">3</div></div><div class="card"><p class="eyebrow">Temas avaliados</p><div class="stat-value mt">8</div></div><div class="card"><p class="eyebrow">Seu plano</p><div class="stat-value mt" style="font-size:29px">Student</div></div></div>' if v=='estudio' else ''
    if v=='ritual':return heading+search+subjects(v)+bar+f'<div class="grid two mt-lg"><div class="card"><div class="journey-note">{ic("leaf")}<div><h3>Pequenos estudos. Novas conexões.</h3><p class="small mt">Não precisa saber por onde começar. Escolha um assunto e deixe a curiosidade fazer o resto.</p></div></div></div><div class="card"><div class="row between"><div><div class="eyebrow">Seu último estudo</div><h3 style="margin-top:10px">Estrutura celular</h3><p class="small">Biologia · ontem</p></div><a href="{href(5)}#history" class="btn secondary" aria-label="Ver histórico">{ic("arrow")}</a></div></div></div>'
    return heading+summary+f'<div class="dashboard-grid"><section>{search}{subjects(v)}{bar}</section>{aside}</div>'
def durations():return '<div class="field mt"><span class="small">Quanto tempo você quer focar?</span><fieldset class="duration-picker" aria-label="Duração do foco">'+''.join(f'<button type="button" data-duration="{n}" aria-pressed="{"true" if n==25 else "false"}">{n} min</button>' for n in [15,25,45,60])+'</fieldset></div>'
def topic(v):
    heading=f'<div class="page-title"><div><a href="{href(1)}" class="text-link mb">{ic("back",True)} Voltar aos assuntos</a><div class="eyebrow">{ "Página 02 / o encontro" if v=="caderno" else "Tema sorteado · pronto para começar"}</div></div>{steps(0)}</div>'
    main=f'''<section class="{'topic-main' if v=='estudio' else ''}"><div class="row">{badge('<span data-subject-name>Biologia</span>')}{badge('<span data-level>Intermediário</span>','neutral')}</div><h1 class="topic-name" data-topic-name>Fotossíntese</h1><p style="max-width:410px">Seu tema está escolhido. Separe seu material, encontre um lugar tranquilo e dê espaço à descoberta.</p>{durations()}<div class="row" style="flex-wrap:wrap">{btn(ic('clock',True)+' Iniciar focus','start-focus')}{btn('Abandonar tema','abandon-topic','ghost')}</div><div class="topic-callout mt-lg"><strong>Ao terminar, explique o que aprendeu.</strong><br>Você terá até 15 minutos para gravar uma explicação e receber seu feedback.</div></section>'''
    aside=f'<aside class="topic-aside"><div class="topic-art">{art()}</div>'+ (f'<div class="card mt"><div class="eyebrow">Sua sessão</div><div class="account-field"><span>Assunto</span><strong data-subject-name>Biologia</strong></div><div class="account-field"><span>Duração escolhida</span><strong><span data-duration-label>25</span> minutos</strong></div><div class="account-field"><span>Depois do foco</span><strong>Explicação por áudio</strong></div><p class="small mt">O score muda depois de uma explicação avaliada.</p></div>' if v=='estudio' else '<p class="small center mt">A próxima conexão começa aqui.</p>')+'</aside>'
    return heading+f'<div class="topic-layout">{main}{aside}</div>'
def focus(v):
    heading=f'<div class="page-title"><div class="eyebrow">{ "Página 03 / presença" if v=="caderno" else "Seu momento de foco"}</div>{steps(1)}</div>'
    shell=f'''<section class="focus-shell"><span class="badge"><span class="dot"></span> Foco em andamento</span><h1 data-topic-name>Fotossíntese</h1><p class="small" style="margin-top:6px"><span data-subject-name>Biologia</span> · <span data-level>Intermediário</span></p><div class="timer-circle"><span class="eyebrow">Tempo restante</span><div class="timer" id="focus-timer" role="timer" aria-label="Tempo restante de foco">24:37</div><p>de <span data-duration-label>25</span> minutos reservados</p></div><div class="focus-actions">{btn('Concluir e explicar '+ic('arrow',True),'complete-focus')}{btn('Abandonar sessão','abandon-focus','ghost')}</div><div class="focus-hint">{ic('headphones')}<p>Estude no seu material. Mantenha esta aba aberta e conectada durante o foco.</p></div></section>'''
    aside=f'''<aside class="stack"><div class="card"><div class="eyebrow">O essencial</div><h3 class="mt">Um tema. Sua atenção.</h3><hr class="rule"><div class="stack"><div class="row">{ic('book')}<span class="small">Abra seu material de estudo.</span></div><div class="row">{ic('headphones')}<span class="small">Diminua as distrações.</span></div><div class="row">{ic('mic')}<span class="small">Prepare-se para explicar.</span></div></div></div><div class="card soft"><h3>Conecte as ideias</h3><p class="small mt">Ao estudar, pense em como contaria isso para alguém que está conhecendo o tema agora.</p></div><p class="small">Você pode concluir antes do tempo. A sessão não tem pausa.</p></aside>'''
    return heading+(f'<div class="focus-dashboard">{shell}{aside}</div>' if v=='estudio' else shell)
def rubric():
    names=['Precisão factual','Cobertura do tema','Raciocínio conceitual','Clareza']
    return '<div class="card"><h3>Sua explicação em detalhe</h3>'+''.join(f'<div class="rubric-row" data-rubric="{i}"><div class="row between"><span>{name}</span><strong><span data-rubric-value>{3 if i==3 else 2}</span> / 4</strong></div><div class="rubric-track">'+''.join(f'<i class="{"filled" if j<(3 if i==3 else 2) else ""}"></i>' for j in range(4))+'</div></div>' for i,name in enumerate(names))+'<p class="small mt">Clareza orienta sua comunicação e não entra na nota de domínio.</p></div>'
TRANSCRIPTS=['Fotossíntese é o processo em que as plantas usam luz, água e gás carbônico para produzir glicose e oxigênio.','Ela acontece nos cloroplastos, e a clorofila captura a energia da luz.','O oxigênio sai do gás carbônico quando a planta quebra o CO2, e a glicose guarda essa energia.','Depois vem o ciclo de Calvin, que precisa receber luz diretamente para montar a glicose.','Esse processo é importante porque coloca oxigênio no ambiente e cria matéria orgânica para a cadeia alimentar.']
def transcript(opened=False,prefix=""):
    seg=''.join(f'<div class="transcript-segment" id="{prefix}segment-{i+1}"><time>{t}</time><span data-segment="{i}">{txt}</span></div>' for i,(t,txt) in enumerate(zip(['00:00','00:15','00:30','00:48','01:08'],TRANSCRIPTS)))
    return f'<div class="card"><details {"open" if opened else ""} id="{prefix}transcript"><summary>Sua transcrição <span class="muted small">1min25 · PT-BR</span></summary><div>{seg}</div><p class="small">Guardamos o texto da sua explicação. O áudio não fica no histórico.</p></details></div>'
def corrections():
    items=[('A origem do oxigênio','O oxigênio sai do gás carbônico…','O oxigênio liberado vem da água, nas reações luminosas. O carbono do CO₂ é incorporado à matéria orgânica.','O oxigênio que sai vem da água que entra.','00:30',3),('A ponte para o ciclo de Calvin','O ciclo de Calvin precisa receber luz diretamente.','O ciclo de Calvin usa ATP e NADPH produzidos nas reações luminosas. Ele não absorve luz diretamente.','A luz carrega as baterias; Calvin usa as baterias.','00:48',4)]
    return '<div class="card"><div class="row between mb"><h3 style="margin:0">Comece por estes ajustes</h3>'+badge('2 pontos','warm')+'</div>'+''.join(f'<article class="correction"><div class="row between"><h4>{i+1:02d}. <span data-correction-title="{i}">{title}</span></h4><a href="#segment-{seg}" class="text-link" data-evidence="segment-{seg}">{ic("volume",True)} {tm}</a></div><blockquote data-claim="{i}">“{claim}”</blockquote><p data-correction="{i}">{body}</p><div class="memory" data-memory="{i}">{ic("leaf",True)} {memory}</div></article>' for i,(title,claim,body,memory,tm,seg) in enumerate(items))+'</div>'
def deep_details():
    return '''<div class="card"><details open><summary>Seu mapa de entendimento</summary><div><div class="concept-row"><span data-concept="0">Função geral da fotossíntese</span><span class="badge">Correto</span></div><div class="concept-row"><span data-concept="1">Reações dependentes de luz</span><span class="badge warm">Parcial</span></div><div class="concept-row"><span data-concept="2">Origem do oxigênio</span><span class="badge danger">Revisar</span></div><div class="concept-row"><span data-concept="3">Ciclo de Calvin</span><span class="badge warm">Parcial</span></div></div></details><details><summary>Como você conectou as ideias</summary><p data-reasoning>Você organizou a explicação por entradas, produtos, local e importância. A conexão se perdeu ao atribuir o O₂ ao CO₂ e ao dizer que Calvin usa luz diretamente.</p><p><strong>Uma conexão melhor:</strong> <span data-better>A luz alimenta as reações que geram ATP e NADPH; essas moléculas levam energia ao ciclo de Calvin.</span></p></details><details><summary>Um roteiro para revisar</summary><ol data-outline><li>Objetivo energético e reagentes do processo.</li><li>Onde ocorrem as duas etapas.</li><li>Como luz e água geram O₂, ATP e NADPH.</li><li>Como ATP e NADPH permitem fixar CO₂.</li><li>Produtos e importância biológica.</li></ol></details><details><summary>Duas perguntas para levar com você</summary><p data-question="0">Se o oxigênio não vem do CO₂, qual reagente fornece seus átomos?</p><p data-question="1">Como a energia capturada pela clorofila chega ao ciclo de Calvin?</p></details></div>'''
def results(v):
    head=f'''<div class="feedback-summary"><div><div class="row">{badge('<span data-verdict>Entendimento parcial</span>','warm')}<span class="small muted" data-topic-name>Fotossíntese</span></div><h2 data-headline>Você viu o todo.<br>Agora, conecte as etapas.</h2><p data-summary>Você identificou os elementos principais. Revisar a origem do oxigênio e a relação entre as etapas vai deixar sua explicação mais consistente.</p></div><div class="mastery"><strong><span data-mastery>50</span><small style="font-size:20px;color:var(--muted)">/100</small></strong><span>Domínio nesta explicação</span></div></div>'''
    strength='<div class="card soft"><div class="row mb">'+ic('check')+'<h3 style="margin:0">O que você fez bem</h3></div><h4 data-strength-title>Boa visão do sistema</h4><p class="small mt" data-strength>Você reuniu reagentes, cloroplastos e importância ecológica numa explicação com começo e consequência.</p></div>'
    score=f'''<div class="card"><div class="eyebrow">Score em <span data-subject-name>Biologia</span></div><div class="row between mt"><div class="stat-value"><span data-before>214</span> <span class="muted" style="font-size:22px">→</span> <span data-after>196</span></div>{badge('<span data-delta>−18</span>','warm')}</div><p class="small mt">O score acompanha as evidências do seu entendimento. Ele pode subir ou descer a cada avaliação.</p><a href="{href(5)}" class="text-link mt">Ver minha evolução {ic('arrow',True)}</a></div>'''
    plan='<div class="card"><h3>Seu próximo passo</h3><p class="small mt" data-plan>Desenhe duas caixas: reações luminosas e ciclo de Calvin. Ligue-as com ATP e NADPH.</p><div class="topic-callout mt"><strong>Como saber se entendeu</strong><p data-criterion>Explique o que entra e sai de cada caixa sem consultar.</p></div></div>'
    if v=='estudio':return head+f'<div class="feedback-columns"><div class="stack">{corrections()}{strength}{deep_details()}</div><div class="stack">{transcript(True)}{rubric()}{score}{plan}</div></div>'
    return head+f'<div class="feedback-columns"><div class="stack">{corrections()}{strength}{transcript()}{deep_details()}</div><div class="stack">{score}{rubric()}{plan}</div></div>'
def feedback(v):
    tabs='<div class="state-tabs" data-prototype-chrome><span>ESTADOS DO PROTÓTIPO</span>'+''.join(f'<button type="button" data-state="{k}" aria-pressed="{"true" if k=="completed" else "false"}">{label}</button>' for k,label in [('active','Gravação'),('pending','Processando'),('completed','Resultado'),('insufficient','Sem evidência'),('failed','Falha'),('expired','Expirado'),('locked','Acesso Student')])+'</div>'
    top=f'<div class="feedback-top"><div><div class="eyebrow mb">{ "Página 04 / o que ficou" if v=="caderno" else "Do estudo ao entendimento"}</div><h1>{ "O que a sua voz revelou." if v=="caderno" else "Sua explicação, mais clara."}</h1></div>{steps(2)}</div>'
    wave='<div class="waveform" aria-hidden="true">'+''.join(f'<i style="height:{h}px"></i>' for h in [8,14,21,12,29,41,25,54,36,68,45,28,52,73,43,26,60,78,48,31,62,42,28,46,22,31,18,24,14,8])+'</div>'
    active=f'''<section data-feedback-panel="active" hidden><div class="recorder card"><div class="record-icon">{ic('mic')}</div><div class="eyebrow mt"><span data-subject-name>Biologia</span> · <span data-topic-name>Fotossíntese</span></div><h2>Explique com suas palavras.</h2><p class="small">Sem ler suas anotações, conte o que você entendeu.<br>Use exemplos e conecte as ideias.</p>{wave}<div class="record-time" id="record-time">00:00</div><p class="small" id="record-label">Pronto para começar · até 15 minutos</p><div class="row mt" style="justify-content:center;flex-wrap:wrap">{btn(ic('mic',True)+' Começar gravação','record')}{btn('Enviar explicação '+ic('arrow',True),'submit','primary','disabled id="submit-audio"')}</div><div class="divider mt">ou envie uma gravação</div><label class="btn secondary mt" for="audio-file">{ic('upload',True)} Escolher áudio</label><input hidden type="file" id="audio-file" accept="audio/webm,audio/ogg,audio/mp4,audio/mpeg,audio/aac,audio/wav,.m4a"><p class="small mt" id="audio-file-label">WebM, Ogg, M4A, MP3, AAC ou WAV · até 32 MiB</p><p class="small mt muted" data-prototype-chrome>Gravação demonstrativa: o microfone não será acessado.</p></div><p class="small center">O tempo para explicar continua contando. Depois, há 2 minutos para concluir o envio.</p></section>'''
    pending=f'''<section data-feedback-panel="pending" hidden><div class="status-card card"><div class="record-icon">{ic('score')}</div><h2>Encontrando as conexões.</h2><p>Sua explicação já virou texto. Estamos avaliando o que você entendeu e onde pode ir além.</p><div class="status-steps"><div class="row accent">{ic('check')} Áudio recebido</div><div class="row accent">{ic('check')} Transcrição concluída</div><div class="row">{ic('clock')} Avaliando sua explicação</div></div>{btn('Ver transcrição','show-transcript','secondary')}<p class="small mt">Seu resultado aparecerá aqui quando estiver pronto.</p></div><div id="pending-transcript" hidden>{transcript(True,"pending-")}</div></section>'''
    completed='<section data-feedback-panel="completed">'+results(v)+f'<div class="row between mt-lg"><p class="small">Um ajuste de cada vez também é aprender.</p>{link("Escolher outro assunto "+ic("arrow",True),1)}</div></section>'
    ins=f'''<section data-feedback-panel="insufficient" hidden><div class="status-card card"><div class="record-icon">{ic('mic')}</div><h2>Ainda faltaram pistas.</h2><p>A explicação não trouxe evidências suficientes sobre o tema para avaliar seu entendimento. Seu score não foi alterado.</p>{badge('Sem nota · score preservado','neutral')}<div class="topic-callout mt" style="text-align:left">Na próxima sessão, apresente a ideia central, explique por que ela funciona e dê um exemplo.</div><div class="mt">{link('Começar um novo estudo '+ic('arrow',True),1)}</div></div></section>'''
    fail=f'''<section data-feedback-panel="failed" hidden><div class="status-card card"><div class="record-icon">{ic('alert')}</div><h2>Não conseguimos concluir a avaliação.</h2><p>Sua transcrição foi preservada. Esta explicação não alterou seu score.</p>{btn('Consultar resultado novamente','refresh-feedback','secondary')}<div class="mt">{link('Voltar aos estudos',1,'ghost')}</div></div>{transcript(True,"failed-")}</section>'''
    expired=f'''<section data-feedback-panel="expired" hidden><div class="status-card card"><div class="record-icon">{ic('clock')}</div><h2>O tempo de envio terminou.</h2><p>Esta explicação expirou antes de ser enviada. Você pode abrir uma nova gravação para o estudo que já concluiu.</p>{btn('Abrir nova explicação','restart-feedback')}</div></section>'''
    locked=f'''<section data-feedback-panel="locked" hidden><div class="status-card card"><div class="record-icon">{ic('lock')}</div>{badge('Student','neutral')}<h2>Dê o próximo passo no seu estudo.</h2><p>Entre na sua conta e tenha o plano Student ativo para receber avaliações da sua explicação.</p><div class="row" style="justify-content:center;flex-wrap:wrap">{link('Entrar na minha conta',0,'secondary')}{btn('Conhecer o Student','plan')}</div><div class="mt">{link('Continuar estudando',1,'ghost')}</div></div></section>'''
    return tabs+top+active+pending+completed+ins+fail+expired+locked

def history():
    rows=[('completed','Fotossíntese','Biologia · Intermediário','Hoje, 09:25','25 min','50/100','−18'),('completed','Estrutura celular','Biologia · Iniciante','Ontem, 18:10','45 min','85/100','+42'),('abandoned','Equações lineares','Matemática · Iniciante','05 set, 14:32','12 de 25 min','Abandonada','—'),('completed','Cinemática','Física · Iniciante','04 set, 10:05','25 min','75/100','+28')]
    output=[]
    for i,(status,title,desc,date,duration,grade,delta) in enumerate(rows):
        action=f'<a class="text-link" href="{href(4)}" aria-label="Abrir feedback de Fotossíntese">{ic("chevron",True)}</a>' if i==0 else f'<button class="text-link" data-action="history-detail" data-history-title="{title}" aria-label="Ver detalhes de {title}">{ic("chevron",True)}</button>'
        output.append(f'<div class="history-row" data-history-status="{status}"><span class="tiny-icon">{ic("check" if status=="completed" else "clock")}</span><div class="grow"><strong class="small">{title}</strong><p style="font-size:10px">{desc} · {date}</p></div><div class="right"><strong class="small">{duration}</strong><p style="font-size:10px">{grade}</p></div><span class="badge {"warm" if delta.startswith("−") else "neutral"}">{delta}</span>{action}</div>')
    return ''.join(output)

def profile(v):
    heading=f'''<div class="page-title"><div class="row"><span class="avatar big">DS</span><div><div class="eyebrow">{ "Seu caderno de descobertas" if v=="caderno" else "Sua jornada até aqui"}</div><h1 style="margin-top:7px">{ "O que você leva consigo." if v=="caderno" else "Cada estudo deixa uma marca."}</h1><p>Daniel Silva <span class="muted">·</span> <span style="font-size:12px">Student</span></p></div></div></div>'''
    stats='<div class="stats mb"><div class="card"><p class="eyebrow">Assuntos explorados</p><div class="stat-value mt">3</div></div><div class="card"><p class="eyebrow">Temas avaliados</p><div class="stat-value mt">9</div></div><div class="card"><p class="eyebrow">Foco concluído</p><div class="stat-value mt">4<small>h</small> 15<small>min</small></div></div></div>'
    scores='<div class="grid three mt">'
    for name,score,count,level in [('Biologia',196,4,'provisório'),('Matemática',342,4,'provisório'),('Física',180,1,'provisório')]:
        scores+=f'<div class="card score-card" data-profile-subject="{name}"><h3>{name}</h3><div class="score"><span data-profile-score>{score}</span><small> / 1.000</small></div><div class="progress"><span style="width:{score/10}%"></span></div><div class="mt">{badge(level.capitalize(),"neutral")}</div><p class="small" data-profile-evaluations style="margin-top:10px">{count} temas distintos · {count} avaliações</p><p class="small" style="margin-top:4px">Nível certificado: <span data-certified>{"Iniciante" if name!="Física" else "em avaliação"}</span></p><p class="small" data-profile-provisional style="margin-top:4px">{"1 tema" if 5-count==1 else str(5-count)+" temas"} para firmar a estimativa</p></div>'
    scores+='</div>'
    account=f'''<aside class="stack"><section class="card" id="account"><div class="eyebrow">Minha conta</div><div class="account-field"><span>Nome</span><strong>Daniel Silva</strong></div><div class="account-field"><span>E-mail</span><strong>daniel@exemplo.com</strong><span class="accent">✓ E-mail verificado</span></div><div class="account-field"><span>Plano</span><strong>Student · ativo</strong></div><div class="account-field"><span>Próxima renovação</span><strong>07 de outubro de 2026</strong></div><div class="mt"><div class="row between small"><span>125 utilizados</span><strong>875 restantes</strong></div><div class="progress" style="margin-top:10px"><span style="width:12.5%"></span></div><p class="small" style="margin-top:8px">de 1.000 créditos do período</p></div>{btn('Gerenciar assinatura '+ic('arrow',True),'billing','secondary','style="width:100%;margin-top:23px"')}<div class="mt center">{btn(ic('logout',True)+' Sair da conta','logout','ghost')}</div></section><section class="card soft"><h3>Score é uma estimativa.</h3><p class="small mt">Mais pontos não significam mais horas. O score considera seu entendimento, a dificuldade e a variedade dos temas.</p><details class="mt"><summary>Como interpretar</summary><p>O score vai de 0 a 1.000 e pode subir ou descer. Fica provisório até reunir evidências de 5 temas distintos. Uma avaliação muda no máximo 100 pontos.</p></details></section></aside>'''
    body=f'''<section>{stats}<div class="row between"><h2>Seu conhecimento por assunto</h2>{ic('score')}</div>{scores}<div class="card mt-lg" id="history"><div class="timeline-heading"><div><div class="eyebrow">Seu percurso</div><h3 style="margin-top:8px">Histórico de estudos</h3></div><fieldset class="filter-chips" aria-label="Filtrar histórico"><button type="button" data-history-filter="all" aria-pressed="true">Todos</button><button type="button" data-history-filter="completed" aria-pressed="false">Concluídos</button><button type="button" data-history-filter="abandoned" aria-pressed="false">Abandonados</button></fieldset></div><div id="history-list">{history()}</div><p id="history-empty" class="small center mt" hidden>Nenhum estudo neste filtro.</p><div class="center mt">{btn('Carregar mais estudos','load-history','secondary')}</div></div></section>'''
    return heading+f'<div class="profile-grid">{body}{account}</div>'
def base_dialogs():
    return '''<dialog class="dialog" id="confirm-dialog" aria-labelledby="dialog-title"><h2 id="dialog-title">Abandonar este estudo?</h2><p id="dialog-copy">Você pode voltar a estudar quando quiser.</p><div class="row"><button class="btn secondary" data-action="close-dialog">Continuar aqui</button><button class="btn danger" id="dialog-confirm">Abandonar</button></div></dialog><dialog class="dialog" id="info-dialog" aria-labelledby="info-title"><h2 id="info-title">Detalhes</h2><p id="info-copy"></p><button class="btn secondary" data-action="close-info">Entendi</button></dialog><div class="toast" id="toast" role="status" hidden></div>'''
RENDER=[login,home,topic,focus,feedback,profile]
def build():
    css=(SRC/'styles.css').read_text()
    js=(SRC/'runtime.js').read_text()
    for v in ['ritual','estudio','caderno']:
        for p,render in enumerate(RENDER):
            body=chrome(v,p,render(v))
            raw=f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>{v.title()} · {TITLES[p]} · JustStudy</title><style>{css}</style></head><body class="{v} {'login-page' if p==0 else ''}" data-page="{NAMES[p]}" data-variant="{v}"><div id="artboard">{body}</div>{base_dialogs()}<script>{js}</script></body></html>'''
            raw=re.sub(r'<button(?![^>]*\btype=)', '<button type="button"',raw)
            (ROOT/v/href(p)).write_text(raw)
    print('18 telas HTML geradas.')
if __name__=='__main__':build()
