CREATE TABLE "knowledge_subjects" (
	"slug" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "knowledge_subjects_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "knowledge_topics" (
	"subject_slug" text NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"level" text NOT NULL,
	CONSTRAINT "knowledge_topics_subject_slug_slug_pk" PRIMARY KEY("subject_slug","slug"),
	CONSTRAINT "knowledge_topics_level_check" CHECK ("knowledge_topics"."level" in ('beginner', 'intermediate', 'advanced', 'specialist'))
);
--> statement-breakpoint
ALTER TABLE "knowledge_topics" ADD CONSTRAINT "knowledge_topics_subject_slug_knowledge_subjects_slug_fk" FOREIGN KEY ("subject_slug") REFERENCES "public"."knowledge_subjects"("slug") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "knowledge_topics_subject_name_index" ON "knowledge_topics" USING btree ("subject_slug","name");--> statement-breakpoint
CREATE INDEX "knowledge_topics_subject_level_index" ON "knowledge_topics" USING btree ("subject_slug","level");--> statement-breakpoint
INSERT INTO "knowledge_subjects" ("slug", "name") VALUES
	('mathematics', 'Mathematics'),
	('statistics', 'Statistics'),
	('physics', 'Physics'),
	('chemistry', 'Chemistry'),
	('biology', 'Biology'),
	('astronomy', 'Astronomy'),
	('earth-science', 'Earth Science'),
	('environmental-science', 'Environmental Science'),
	('computer-science', 'Computer Science'),
	('software-engineering', 'Software Engineering'),
	('electrical-engineering', 'Electrical Engineering'),
	('mechanical-engineering', 'Mechanical Engineering'),
	('civil-engineering', 'Civil Engineering'),
	('medicine', 'Medicine'),
	('neuroscience', 'Neuroscience'),
	('psychology', 'Psychology'),
	('history', 'History'),
	('geography', 'Geography'),
	('philosophy', 'Philosophy'),
	('linguistics', 'Linguistics'),
	('literature', 'Literature'),
	('sociology', 'Sociology'),
	('anthropology', 'Anthropology'),
	('economics', 'Economics'),
	('political-science', 'Political Science'),
	('law', 'Law'),
	('art-history', 'Art History'),
	('music-theory', 'Music Theory'),
	('architecture', 'Architecture'),
	('finance', 'Finance');--> statement-breakpoint
WITH catalog(subject_slug, level, names) AS (VALUES
	('mathematics', 'beginner', ARRAY[
		'Natural Numbers', 'Integers', 'Fractions', 'Decimal Numbers', 'Ratios and Proportions',
		'Percentages', 'Exponents and Roots', 'Order of Operations', 'Linear Equations',
		'Cartesian Coordinate Plane', 'Angles', 'Triangles', 'Quadrilaterals', 'Circles',
		'Area and Volume'
	]::text[]),
	('mathematics', 'intermediate', ARRAY[
		'Systems of Linear Equations', 'Linear Inequalities', 'Polynomial Operations',
		'Polynomial Factorization', 'Quadratic Equations', 'Functions and Domains',
		'Function Transformations', 'Arithmetic Sequences', 'Geometric Sequences',
		'Infinite Series', 'Logarithms', 'Complex Numbers', 'Analytic Geometry', 'Conic Sections',
		'Trigonometric Ratios', 'Unit Circle', 'Trigonometric Identities', 'Euclidean Vectors',
		'Matrix Operations', 'Determinants', 'Permutations', 'Combinations', 'Binomial Theorem',
		'Mathematical Induction', 'Set Theory', 'Equivalence Relations', 'Modular Arithmetic',
		'Prime Numbers', 'Greatest Common Divisors', 'Euclidean Algorithm', 'Graph Theory',
		'Tree Structures', 'Limits', 'Continuity', 'Mathematical Proof Techniques'
	]::text[]),
	('mathematics', 'advanced', ARRAY[
		'Differential Calculus', 'Integral Calculus', 'Multivariable Calculus',
		'Partial Derivatives', 'Multiple Integrals', 'Vector Calculus',
		'Ordinary Differential Equations', 'Fourier Series', 'Laplace Transforms', 'Real Analysis',
		'Metric Spaces', 'Point-Set Topology', 'Group Theory', 'Ring Theory', 'Field Theory',
		'Linear Transformations', 'Eigenvalues and Eigenvectors', 'Numerical Analysis',
		'Convex Optimization', 'Elementary Number Theory', 'Generating Functions',
		'Recurrence Relations', 'Boolean Algebra', 'Measure Theory', 'Tensor Algebra',
		'Differential Geometry', 'Complex Analysis', 'Calculus of Variations',
		'Dynamical Systems', 'Discrete Geometry'
	]::text[]),
	('mathematics', 'specialist', ARRAY[
		'Galois Theory', 'Algebraic Topology', 'Category Theory', 'Homological Algebra',
		'Functional Analysis', 'Operator Theory', 'Lie Groups', 'Lie Algebras',
		'Algebraic Geometry', 'Analytic Number Theory', 'Algebraic Number Theory',
		'Representation Theory', 'Partial Differential Equations', 'Riemannian Geometry',
		'Symplectic Geometry', 'Ergodic Theory', 'Model Theory', 'Proof Theory',
		'Set-Theoretic Forcing', 'Noncommutative Geometry'
	]::text[]),
	('statistics', 'beginner', ARRAY[
		'Populations and Samples', 'Categorical Variables', 'Numerical Variables',
		'Frequency Distributions', 'Bar Charts', 'Histograms', 'Arithmetic Mean', 'Median', 'Mode',
		'Range', 'Percentiles', 'Quartiles', 'Variance', 'Standard Deviation',
		'Basic Probability'
	]::text[]),
	('statistics', 'intermediate', ARRAY[
		'Random Variables', 'Discrete Probability Distributions',
		'Continuous Probability Distributions', 'Expected Value', 'Conditional Probability',
		'Bayes'' Theorem', 'Independence', 'Binomial Distribution', 'Poisson Distribution',
		'Normal Distribution', 'Exponential Distribution', 'Sampling Distributions',
		'Central Limit Theorem', 'Confidence Intervals', 'Hypothesis Testing', 'P-Values',
		'Type I and Type II Errors', 'Statistical Power', 'Correlation', 'Simple Linear Regression',
		'Least Squares Estimation', 'Residual Analysis', 'Analysis of Variance',
		'Chi-Square Tests', 'Nonparametric Tests', 'Bootstrapping', 'Stratified Sampling',
		'Cluster Sampling', 'Survey Bias', 'Missing Data Mechanisms', 'Outlier Detection',
		'Effect Size', 'Contingency Tables', 'Probability Generating Functions',
		'Exploratory Data Analysis'
	]::text[]),
	('statistics', 'advanced', ARRAY[
		'Multiple Linear Regression', 'Generalized Linear Models', 'Logistic Regression',
		'Poisson Regression', 'Mixed-Effects Models', 'Survival Analysis',
		'Kaplan-Meier Estimation', 'Cox Proportional Hazards Model', 'Time Series Analysis',
		'Autoregressive Integrated Moving Average Models', 'State Space Models',
		'Bayesian Inference', 'Markov Chain Monte Carlo', 'Maximum Likelihood Estimation',
		'Fisher Information', 'Likelihood Ratio Tests', 'Multivariate Analysis',
		'Principal Component Analysis', 'Factor Analysis', 'Canonical Correlation',
		'Experimental Design', 'Randomized Controlled Trials', 'Causal Diagrams',
		'Propensity Score Methods', 'Instrumental Variables', 'Multiple Imputation',
		'False Discovery Rate', 'Kernel Density Estimation', 'Monte Carlo Simulation',
		'Empirical Bayes Methods'
	]::text[]),
	('statistics', 'specialist', ARRAY[
		'Measure-Theoretic Probability', 'Asymptotic Statistics', 'Semiparametric Efficiency',
		'Nonparametric Bayesian Models', 'Gaussian Processes', 'Copula Models',
		'Extreme Value Theory', 'Spatial Statistics', 'Functional Data Analysis',
		'High-Dimensional Statistics', 'Sparse Regression', 'Concentration Inequalities',
		'Empirical Process Theory', 'Martingale Central Limit Theorems',
		'Stochastic Differential Equations', 'Bayesian Nonparametrics',
		'Causal Mediation Analysis', 'Targeted Maximum Likelihood Estimation',
		'Optimal Transport Statistics', 'Algebraic Statistics'
	]::text[]),
	('physics', 'beginner', ARRAY[
		'Physical Quantities and Units', 'Scalar and Vector Quantities', 'Position and Displacement',
		'Speed and Velocity', 'Acceleration', 'Newton''s Laws of Motion', 'Mass and Weight',
		'Friction', 'Work and Energy', 'Power', 'Momentum', 'Pressure', 'Temperature',
		'Waves', 'Electric Charge'
	]::text[]),
	('physics', 'intermediate', ARRAY[
		'Projectile Motion', 'Uniform Circular Motion', 'Rotational Kinematics', 'Torque',
		'Angular Momentum', 'Static Equilibrium', 'Simple Harmonic Motion', 'Hooke''s Law',
		'Conservation of Mechanical Energy', 'Conservation of Linear Momentum',
		'Fluid Statics', 'Bernoulli Principle', 'Ideal Gas Law', 'Kinetic Theory of Gases',
		'First Law of Thermodynamics', 'Entropy', 'Heat Transfer', 'Wave Interference',
		'Standing Waves', 'Doppler Effect', 'Geometric Optics', 'Lenses and Mirrors',
		'Wave Optics', 'Coulomb''s Law', 'Electric Fields', 'Electric Potential',
		'Direct Current Circuits', 'Kirchhoff''s Circuit Laws', 'Magnetic Fields',
		'Electromagnetic Induction', 'Alternating Current', 'Special Relativity',
		'Photoelectric Effect', 'Atomic Spectra', 'Radioactive Decay'
	]::text[]),
	('physics', 'advanced', ARRAY[
		'Lagrangian Mechanics', 'Hamiltonian Mechanics', 'Rigid Body Dynamics',
		'Nonlinear Oscillations', 'Navier-Stokes Equations', 'Thermodynamic Potentials',
		'Statistical Mechanics', 'Maxwell Equations', 'Electromagnetic Waves',
		'Gauge Transformations', 'Lorentz Transformations', 'General Relativity',
		'Quantum Wavefunctions', 'Schrodinger Equation', 'Quantum Operators',
		'Angular Momentum in Quantum Mechanics', 'Quantum Tunneling', 'Spin Systems',
		'Perturbation Theory', 'Identical Particles', 'Solid-State Band Theory',
		'Semiconductor Physics', 'Superconductivity', 'Nuclear Structure', 'Particle Detectors',
		'Plasma Physics', 'Radiative Transfer', 'Chaos Theory', 'Continuum Mechanics',
		'Green Functions in Physics'
	]::text[]),
	('physics', 'specialist', ARRAY[
		'Quantum Field Theory', 'Quantum Electrodynamics', 'Quantum Chromodynamics',
		'Standard Model of Particle Physics', 'Spontaneous Symmetry Breaking',
		'Renormalization Group', 'Path Integral Formulation', 'General Relativistic Cosmology',
		'Black Hole Thermodynamics', 'Gravitational Wave Physics', 'String Theory',
		'Loop Quantum Gravity', 'Topological Quantum Field Theory',
		'Conformal Field Theory', 'Many-Body Quantum Physics', 'Quantum Information Theory',
		'Topological Phases of Matter', 'Neutrino Oscillations', 'Magnetohydrodynamics',
		'Nonequilibrium Statistical Mechanics'
	]::text[]),
	('chemistry', 'beginner', ARRAY[
		'Atoms and Elements', 'Chemical Symbols', 'Periodic Table', 'Atomic Mass', 'Molecules',
		'Ions', 'Chemical Formulas', 'Chemical Bonds', 'States of Matter', 'Physical Changes',
		'Chemical Reactions', 'Acids and Bases', 'Solutions', 'Mixtures and Pure Substances',
		'Laboratory Safety'
	]::text[]),
	('chemistry', 'intermediate', ARRAY[
		'Atomic Orbitals', 'Electron Configurations', 'Periodic Trends', 'Ionic Bonding',
		'Covalent Bonding', 'Metallic Bonding', 'Lewis Structures',
		'Valence Shell Electron Pair Repulsion Theory', 'Molecular Polarity',
		'Intermolecular Forces', 'Chemical Nomenclature', 'Mole Concept',
		'Stoichiometry', 'Limiting Reagents', 'Solution Concentration', 'Gas Stoichiometry',
		'Thermochemistry', 'Hess''s Law', 'Reaction Rates', 'Chemical Equilibrium',
		'Le Chatelier Principle', 'Acid-Base Equilibria', 'Buffer Solutions',
		'Solubility Equilibria', 'Oxidation States', 'Redox Reactions',
		'Electrochemical Cells', 'Organic Functional Groups', 'Hydrocarbons',
		'Stereoisomers', 'Substitution Reactions', 'Elimination Reactions',
		'Addition Reactions', 'Polymer Chemistry', 'Chemical Spectroscopy'
	]::text[]),
	('chemistry', 'advanced', ARRAY[
		'Quantum Chemistry', 'Molecular Orbital Theory', 'Crystal Field Theory',
		'Ligand Field Theory', 'Coordination Chemistry', 'Organometallic Chemistry',
		'Chemical Thermodynamics', 'Phase Equilibria', 'Statistical Thermodynamics',
		'Chemical Kinetics', 'Transition State Theory', 'Catalysis',
		'Surface Chemistry', 'Colloid Chemistry', 'Electrochemical Kinetics',
		'Organic Reaction Mechanisms', 'Pericyclic Reactions', 'Aromaticity',
		'Retrosynthetic Analysis', 'Asymmetric Synthesis', 'Heterocyclic Chemistry',
		'Biomolecular Chemistry', 'Protein Chemistry', 'Nucleic Acid Chemistry',
		'Nuclear Magnetic Resonance Spectroscopy', 'Mass Spectrometry',
		'X-Ray Crystallography', 'Chromatographic Separation', 'Environmental Chemistry',
		'Materials Chemistry'
	]::text[]),
	('chemistry', 'specialist', ARRAY[
		'Computational Electronic Structure', 'Density Functional Theory',
		'Coupled Cluster Methods', 'Femtochemistry', 'Ultrafast Spectroscopy',
		'Supramolecular Chemistry', 'Host-Guest Chemistry', 'Molecular Self-Assembly',
		'Total Synthesis of Natural Products', 'Chemical Biology',
		'Bioorthogonal Chemistry', 'Single-Molecule Spectroscopy', 'Solid-State Nuclear Magnetic Resonance',
		'Electrocatalysis', 'Photocatalysis', 'Homogeneous Catalysis',
		'Nanoparticle Surface Chemistry', 'Metal-Organic Frameworks',
		'Flow Chemistry', 'Mechanochemistry'
	]::text[]),
	('biology', 'beginner', ARRAY[
		'Characteristics of Life', 'Cell Theory', 'Prokaryotic Cells', 'Eukaryotic Cells',
		'Cell Membranes', 'Cell Organelles', 'Photosynthesis', 'Cellular Respiration',
		'Deoxyribonucleic Acid', 'Genes and Chromosomes', 'Mitosis', 'Meiosis',
		'Natural Selection', 'Biological Classification', 'Ecosystems'
	]::text[]),
	('biology', 'intermediate', ARRAY[
		'Macromolecules of Life', 'Enzyme Function', 'Membrane Transport', 'Cell Signaling',
		'Cell Cycle Regulation', 'Mendelian Genetics', 'Genetic Recombination',
		'Gene Expression', 'Protein Synthesis', 'Mutations', 'Population Genetics',
		'Evolutionary Adaptation', 'Speciation', 'Phylogenetic Trees',
		'Microbial Diversity', 'Plant Anatomy', 'Plant Hormones', 'Animal Tissues',
		'Human Organ Systems', 'Innate Immunity', 'Adaptive Immunity', 'Homeostasis',
		'Reproductive Biology', 'Embryonic Development', 'Behavioral Ecology',
		'Population Ecology', 'Community Ecology', 'Food Webs', 'Biogeochemical Cycles',
		'Biodiversity', 'Conservation Biology', 'Symbiosis', 'Parasitism',
		'Aquatic Ecology', 'Terrestrial Biomes'
	]::text[]),
	('biology', 'advanced', ARRAY[
		'Molecular Genetics', 'Epigenetic Regulation', 'Genome Organization',
		'Recombinant DNA Technology', 'Genome Editing', 'Transcriptomics', 'Proteomics',
		'Metabolic Pathways', 'Mitochondrial Bioenergetics', 'Cytoskeletal Dynamics',
		'Intracellular Trafficking', 'Programmed Cell Death', 'Stem Cell Biology',
		'Developmental Patterning', 'Evolutionary Developmental Biology',
		'Quantitative Genetics', 'Molecular Evolution', 'Microbial Metabolism',
		'Virology', 'Immunological Memory', 'Neurobiology', 'Endocrine Regulation',
		'Comparative Physiology', 'Systems Ecology', 'Island Biogeography',
		'Landscape Ecology', 'Coevolution', 'Social Evolution', 'Biological Rhythms',
		'Synthetic Biology'
	]::text[]),
	('biology', 'specialist', ARRAY[
		'Single-Cell Genomics', 'Spatial Transcriptomics', 'Chromatin Architecture',
		'Ribonucleic Acid Epigenetics', 'Protein Folding Landscapes',
		'Intrinsically Disordered Proteins', 'Phase Separation in Cells',
		'Mechanobiology', 'Organoid Biology', 'Cellular Reprogramming',
		'Immune Repertoire Sequencing', 'Microbiome Systems Biology',
		'Metagenomic Assembly', 'Ancestral Sequence Reconstruction',
		'Experimental Evolution', 'Theoretical Population Genetics',
		'Ecological Network Theory', 'Phylogenomics', 'Astrobiology',
		'Origins of Cellular Life'
	]::text[]),
	('astronomy', 'beginner', ARRAY[
		'Celestial Sphere', 'Day and Night Cycle', 'Phases of the Moon', 'Solar Eclipses',
		'Lunar Eclipses', 'Seasons', 'Terrestrial Planets', 'Gas Giant Planets',
		'Dwarf Planets', 'Asteroids', 'Comets', 'The Sun', 'Stars', 'Galaxies',
		'Light-Years'
	]::text[]),
	('astronomy', 'intermediate', ARRAY[
		'Orbital Motion', 'Kepler''s Laws of Planetary Motion', 'Newton''s Law of Gravitation',
		'Escape Velocity', 'Tidal Forces', 'Planetary Atmospheres', 'Exoplanet Detection',
		'Habitable Zones', 'Solar Interior', 'Solar Activity', 'Stellar Parallax',
		'Apparent and Absolute Magnitude', 'Stellar Spectra', 'Hertzsprung-Russell Diagram',
		'Star Formation', 'Main-Sequence Stars', 'Red Giant Stars', 'White Dwarf Stars',
		'Neutron Stars', 'Stellar Black Holes', 'Supernovae', 'Open Star Clusters',
		'Globular Star Clusters', 'Milky Way Structure', 'Spiral Galaxies',
		'Elliptical Galaxies', 'Active Galactic Nuclei', 'Galaxy Clusters', 'Dark Matter',
		'Cosmic Expansion', 'Big Bang Cosmology', 'Cosmic Microwave Background',
		'Optical Telescopes', 'Radio Telescopes', 'Astronomical Coordinates'
	]::text[]),
	('astronomy', 'advanced', ARRAY[
		'Celestial Mechanics', 'Orbital Resonance', 'Planetary Formation',
		'Protoplanetary Disks', 'Exoplanet Atmospheres', 'Stellar Nucleosynthesis',
		'Stellar Evolution Models', 'Asteroseismology', 'Binary Star Evolution',
		'Accretion Disks', 'Pulsars', 'Magnetars', 'Gamma-Ray Bursts',
		'Gravitational Lensing', 'Galaxy Formation', 'Galaxy Rotation Curves',
		'Interstellar Medium', 'Galactic Dynamics', 'Large-Scale Cosmic Structure',
		'Dark Energy', 'Cosmological Redshift', 'Distance Ladder',
		'Baryon Acoustic Oscillations', 'Primordial Nucleosynthesis', 'Neutrino Astronomy',
		'X-Ray Astronomy', 'Infrared Astronomy', 'Adaptive Optics',
		'Astronomical Interferometry', 'Astrometric Measurement'
	]::text[]),
	('astronomy', 'specialist', ARRAY[
		'Relativistic Astrophysics', 'Black Hole Accretion Physics',
		'Numerical Relativity', 'Gravitational Wave Astronomy',
		'Cosmic Inflation', 'Early-Universe Phase Transitions', 'Reionization Epoch',
		'Cosmic Microwave Background Polarization', 'Modified Gravity Cosmology',
		'Precision Cosmological Parameter Estimation', 'Stellar Magnetohydrodynamics',
		'Radiation Hydrodynamics', 'Compact Object Merger Physics',
		'Fast Radio Bursts', 'High-Energy Cosmic Rays', 'Extragalactic Distance Scale',
		'Galactic Archaeology', 'Computational Galaxy Formation',
		'Exoplanet Biosignatures', 'Technosignature Astronomy'
	]::text[]),
	('earth-science', 'beginner', ARRAY[
		'Earth''s Internal Layers', 'Minerals', 'Rocks', 'Rock Cycle', 'Plate Tectonics',
		'Earthquakes', 'Volcanoes', 'Mountains', 'Weathering', 'Erosion', 'Soil',
		'Water Cycle', 'Oceans', 'Atmosphere', 'Geologic Time'
	]::text[]),
	('earth-science', 'intermediate', ARRAY[
		'Mineral Identification', 'Igneous Rocks', 'Sedimentary Rocks', 'Metamorphic Rocks',
		'Magma Differentiation', 'Continental Drift', 'Seafloor Spreading',
		'Subduction Zones', 'Transform Faults', 'Earthquake Waves', 'Earthquake Magnitude',
		'Volcanic Landforms', 'River Systems', 'Groundwater Aquifers', 'Karst Landscapes',
		'Glaciers', 'Desert Landforms', 'Coastal Processes', 'Soil Horizons',
		'Fossil Formation', 'Relative Geologic Dating', 'Radiometric Dating',
		'Stratigraphic Principles', 'Paleoclimate Evidence', 'Ocean Currents',
		'Ocean Tides', 'Marine Sediments', 'Atmospheric Pressure', 'Cloud Formation',
		'Weather Fronts', 'Tropical Cyclones', 'Climate Zones', 'Carbon Cycle',
		'Geomagnetic Field', 'Remote Sensing of Earth'
	]::text[]),
	('earth-science', 'advanced', ARRAY[
		'Seismic Tomography', 'Mantle Convection', 'Crustal Deformation',
		'Isostatic Equilibrium', 'Tectonic Basin Analysis', 'Structural Geology',
		'Petrology', 'Geochemistry', 'Isotope Geology', 'Economic Geology',
		'Hydrogeology', 'Fluvial Geomorphology', 'Glacial Geomorphology',
		'Quaternary Geology', 'Sequence Stratigraphy', 'Paleomagnetism',
		'Paleontology', 'Paleoceanography', 'Physical Oceanography',
		'Chemical Oceanography', 'Atmospheric Dynamics', 'Synoptic Meteorology',
		'Boundary Layer Meteorology', 'Climate Modeling', 'Ice Core Analysis',
		'Geochronology', 'Geographic Information Systems', 'Satellite Geodesy',
		'Natural Hazard Assessment', 'Planetary Geology'
	]::text[]),
	('earth-science', 'specialist', ARRAY[
		'Deep Earth Mineral Physics', 'High-Pressure Geochemistry',
		'Thermochronology', 'Metamorphic Phase Equilibria', 'Fault Zone Mechanics',
		'Earthquake Source Inversion', 'Crustal Rheology', 'Geodynamic Modeling',
		'Geoneutrino Science', 'Geomagnetic Dynamo Theory', 'Stable Isotope Paleoclimatology',
		'Clumped Isotope Thermometry', 'Organic Geochemistry',
		'Sedimentary Provenance Analysis', 'Subsurface Reactive Transport',
		'Turbulence in Geophysical Fluids', 'Data Assimilation in Meteorology',
		'Cloud Microphysics', 'Coupled Climate System Dynamics',
		'Anthropocene Stratigraphy'
	]::text[]),
	('environmental-science', 'beginner', ARRAY[
		'Natural Resources', 'Renewable Resources', 'Nonrenewable Resources',
		'Biodiversity', 'Habitats', 'Food Chains', 'Water Pollution', 'Air Pollution',
		'Soil Pollution', 'Waste Management', 'Recycling', 'Climate Change',
		'Deforestation', 'Conservation', 'Sustainable Development'
	]::text[]),
	('environmental-science', 'intermediate', ARRAY[
		'Ecosystem Services', 'Ecological Footprints', 'Carrying Capacity',
		'Habitat Fragmentation', 'Invasive Species', 'Endangered Species Conservation',
		'Protected Areas', 'Watershed Management', 'Eutrophication', 'Groundwater Contamination',
		'Drinking Water Treatment', 'Wastewater Treatment', 'Particulate Air Pollution',
		'Photochemical Smog', 'Acid Deposition', 'Ozone Layer Depletion',
		'Greenhouse Gas Emissions', 'Carbon Footprints', 'Climate Mitigation',
		'Climate Adaptation', 'Environmental Toxicology', 'Bioaccumulation',
		'Biomagnification', 'Solid Waste Landfills', 'Hazardous Waste',
		'Circular Economy', 'Life-Cycle Assessment', 'Environmental Impact Assessment',
		'Environmental Justice', 'Renewable Energy Systems', 'Energy Efficiency',
		'Sustainable Agriculture', 'Urban Sustainability', 'Marine Conservation',
		'Environmental Policy Instruments'
	]::text[]),
	('environmental-science', 'advanced', ARRAY[
		'Population Viability Analysis', 'Conservation Genetics', 'Restoration Ecology',
		'Landscape Connectivity', 'Freshwater Ecology', 'Marine Ecosystem Management',
		'Biogeochemical Modeling', 'Environmental Microbiology',
		'Contaminant Fate and Transport', 'Ecological Risk Assessment',
		'Human Health Risk Assessment', 'Industrial Ecology', 'Material Flow Analysis',
		'Carbon Accounting', 'Emissions Trading Systems', 'Integrated Assessment Models',
		'Climate Vulnerability Assessment', 'Disaster Risk Reduction',
		'Environmental Economics', 'Common-Pool Resource Governance',
		'Sustainability Transitions', 'Agroecology', 'Regenerative Agriculture',
		'Forest Carbon Dynamics', 'Wetland Ecology', 'Ocean Acidification',
		'Coastal Zone Management', 'Environmental Remote Sensing',
		'Green Infrastructure', 'Nature-Based Solutions'
	]::text[]),
	('environmental-science', 'specialist', ARRAY[
		'Earth System Modeling', 'Climate Attribution Science',
		'Climate Tipping Elements', 'Coupled Human-Natural Systems',
		'Planetary Boundaries', 'Biodiversity-Ecosystem Function Relationships',
		'Ecological Network Resilience', 'Adaptive Environmental Governance',
		'Environmental DNA Monitoring', 'Pollutant Mixture Toxicology',
		'Persistent Organic Pollutants', 'Perfluoroalkyl Substance Remediation',
		'Bioremediation Engineering', 'Direct Air Carbon Capture',
		'Carbon Dioxide Removal Verification', 'Solar Radiation Modification Governance',
		'Degrowth Economics', 'Socioecological Metabolism',
		'Intergenerational Climate Justice', 'Deep-Sea Mining Impacts'
	]::text[]),
	('computer-science', 'beginner', ARRAY[
		'Binary Numbers', 'Boolean Logic', 'Computer Hardware', 'Operating Systems',
		'Files and Directories', 'Computer Networks', 'Algorithms', 'Variables and Data Types',
		'Conditional Statements', 'Loops', 'Functions', 'Arrays', 'Text Encoding',
		'Debugging', 'Version Control'
	]::text[]),
	('computer-science', 'intermediate', ARRAY[
		'Algorithmic Complexity', 'Recursion', 'Linked Lists', 'Stacks', 'Queues', 'Hash Tables',
		'Binary Search Trees', 'Heaps', 'Graph Traversal', 'Sorting Algorithms',
		'Search Algorithms', 'Greedy Algorithms', 'Dynamic Programming',
		'Object-Oriented Programming', 'Functional Programming', 'Type Systems',
		'Memory Management', 'Processes and Threads', 'Concurrency',
		'Central Processing Unit Cache Hierarchies', 'Virtual Memory', 'File Systems',
		'Relational Databases', 'Structured Query Language', 'Database Indexes',
		'Database Transactions', 'Internet Protocol Suite', 'Domain Name System',
		'Hypertext Transfer Protocol', 'Public-Key Cryptography', 'Symmetric Cryptography',
		'Web Application Architecture', 'Compiler Phases', 'Finite Automata',
		'Computability'
	]::text[]),
	('computer-science', 'advanced', ARRAY[
		'Balanced Search Trees', 'Probabilistic Data Structures', 'Graph Algorithms',
		'Network Flow Algorithms', 'Approximation Algorithms', 'Randomized Algorithms',
		'Parallel Algorithms', 'Garbage Collection', 'Operating System Scheduling',
		'Distributed Systems', 'Consensus Algorithms', 'Replication Protocols',
		'Database Query Optimization', 'Multi-Version Concurrency Control',
		'Column-Oriented Databases', 'Computer Architecture', 'Instruction Pipelines',
		'Cache Coherence', 'Computer Networks Routing', 'Congestion Control',
		'Applied Cryptography', 'Zero-Knowledge Proofs', 'Programming Language Semantics',
		'Static Program Analysis', 'Compiler Optimization', 'Formal Languages',
		'Computational Complexity', 'Machine Learning', 'Neural Networks',
		'Information Retrieval'
	]::text[]),
	('computer-science', 'specialist', ARRAY[
		'Parameterized Complexity', 'Communication Complexity',
		'Quantum Computing Algorithms', 'Homomorphic Encryption',
		'Secure Multiparty Computation', 'Post-Quantum Cryptography',
		'Byzantine Fault Tolerance', 'Conflict-Free Replicated Data Types',
		'Distributed Transaction Protocols', 'Verified Compilation',
		'Dependent Type Theory', 'Program Synthesis', 'Model Checking',
		'Abstract Interpretation', 'Concurrent Separation Logic',
		'Differentiable Programming', 'Large Language Models',
		'Graph Neural Networks', 'Computer Vision Transformers',
		'Computational Geometry'
	]::text[]),
	('software-engineering', 'beginner', ARRAY[
		'Software Requirements', 'Source Code', 'Programming Interfaces', 'Code Compilation',
		'Runtime Errors', 'Unit Testing', 'Code Reviews', 'Version Control Workflows',
		'Issue Tracking', 'Software Releases', 'Documentation', 'Configuration Files',
		'Command-Line Interfaces', 'Client-Server Applications', 'Software Maintenance'
	]::text[]),
	('software-engineering', 'intermediate', ARRAY[
		'SOLID Principles', 'Separation of Concerns', 'Dependency Inversion',
		'Interface Segregation', 'Composition over Inheritance', 'Design by Contract',
		'Application Layering', 'Modular Monoliths', 'Microservice Architecture',
		'Event-Driven Architecture', 'Application Programming Interface Design',
		'Resource-Oriented APIs', 'Backward Compatibility', 'Semantic Versioning',
		'Database Schema Design', 'Database Migrations', 'Transaction Boundaries',
		'Idempotent Operations', 'Caching Strategies', 'Message Queues',
		'Background Jobs', 'Structured Logging', 'Application Metrics',
		'Distributed Tracing', 'Feature Flags', 'Continuous Integration',
		'Continuous Delivery', 'Containerized Applications', 'Infrastructure as Code',
		'Test Doubles', 'Integration Testing', 'End-to-End Testing',
		'Property-Based Testing', 'Threat Modeling', 'Secure Coding'
	]::text[]),
	('software-engineering', 'advanced', ARRAY[
		'Hexagonal Architecture', 'Clean Architecture', 'Command Query Responsibility Segregation',
		'Event Sourcing', 'Saga Transactions', 'Transactional Outbox', 'Change Data Capture',
		'Distributed System Observability', 'Service-Level Objectives',
		'Error Budgets', 'Load Shedding', 'Circuit Breakers', 'Bulkhead Isolation',
		'Rate Limiting', 'Distributed Caching', 'Data Partitioning', 'Zero-Downtime Migrations',
		'Blue-Green Deployment', 'Canary Deployment', 'Chaos Engineering',
		'Performance Profiling', 'Memory Leak Diagnosis', 'Concurrency Testing',
		'Contract Testing', 'Mutation Testing', 'Supply Chain Security',
		'Authentication Protocol Design', 'Authorization Models',
		'Multitenant Architecture', 'Legacy System Modernization'
	]::text[]),
	('software-engineering', 'specialist', ARRAY[
		'Formal Software Specification', 'Safety-Critical Software Engineering',
		'Deterministic Distributed Simulation', 'Globally Distributed Database Design',
		'Consensus-Backed Service Architecture', 'Exactly-Once Processing Semantics',
		'High-Availability Capacity Planning', 'Tail Latency Engineering',
		'Kernel-Level Performance Analysis', 'Lock-Free Data Structures',
		'Programming Language Runtime Design', 'Reproducible Build Systems',
		'Progressive Delivery Control Theory', 'Production Traffic Shadowing',
		'Large-Scale Incident Command', 'Software Architecture Fitness Functions',
		'Automated Program Repair', 'Software Model Checking',
		'Privacy-Preserving System Design', 'Postmortem Learning Systems'
	]::text[]),
	('electrical-engineering', 'beginner', ARRAY[
		'Electric Charge', 'Electric Current', 'Voltage', 'Electrical Resistance', 'Ohms Law',
		'Electrical Power', 'Series Circuits', 'Parallel Circuits', 'Circuit Diagrams',
		'Conductors and Insulators', 'Direct Current', 'Alternating Current', 'Magnets',
		'Electromagnets', 'Electrical Safety'
	]::text[]),
	('electrical-engineering', 'intermediate', ARRAY[
		'Kirchhoff''s Current Law', 'Kirchhoff''s Voltage Law', 'Node Voltage Analysis',
		'Mesh Current Analysis', 'Thevenin Equivalent Circuits', 'Norton Equivalent Circuits',
		'Capacitors', 'Inductors', 'First-Order Circuits', 'Second-Order Circuits',
		'Sinusoidal Steady State', 'Electrical Impedance', 'Resonant Circuits',
		'Three-Phase Power', 'Transformers', 'Direct Current Motors',
		'Alternating Current Motors', 'Synchronous Generators', 'Diodes',
		'Bipolar Junction Transistors', 'Field-Effect Transistors',
		'Operational Amplifiers', 'Analog Filters', 'Digital Logic Gates',
		'Combinational Logic', 'Sequential Logic', 'Flip-Flops', 'Analog-to-Digital Conversion',
		'Digital-to-Analog Conversion', 'Pulse-Width Modulation', 'Feedback Control',
		'Frequency Response', 'Transmission Lines', 'Antennas', 'Electromagnetic Compatibility'
	]::text[]),
	('electrical-engineering', 'advanced', ARRAY[
		'Semiconductor Device Physics', 'Integrated Circuit Design', 'Complementary Metal-Oxide Semiconductors',
		'Power Electronics', 'Switch-Mode Power Supplies', 'Electric Drive Control',
		'Power System Load Flow', 'Power System Fault Analysis', 'Protective Relaying',
		'Smart Electrical Grids', 'State-Space Control', 'Optimal Control',
		'Digital Signal Processing', 'Discrete Fourier Transform', 'Digital Filter Design',
		'Random Signal Analysis', 'Communication System Modulation', 'Error-Correcting Codes',
		'Radio-Frequency Circuit Design', 'Microwave Engineering', 'Waveguides',
		'Antenna Arrays', 'Embedded Systems', 'Real-Time Operating Systems',
		'Field-Programmable Gate Arrays', 'Hardware Description Languages',
		'Very-Large-Scale Integration', 'Sensor Instrumentation', 'Optoelectronics',
		'Electrical Energy Storage'
	]::text[]),
	('electrical-engineering', 'specialist', ARRAY[
		'Subthreshold Integrated Circuit Design', 'Mixed-Signal Integrated Circuits',
		'Millimeter-Wave Circuit Design', 'Terahertz Electronics',
		'Silicon Photonics', 'Quantum Electronic Devices', 'Wide-Bandgap Power Semiconductors',
		'Multilevel Power Converters', 'High-Voltage Direct Current Transmission',
		'Power System Transient Stability', 'Grid-Forming Inverters',
		'Model Predictive Control for Power Electronics', 'Massive Multiple-Input Multiple-Output Systems',
		'Orthogonal Frequency-Division Multiplexing', 'Software-Defined Radio',
		'Phased-Array Beamforming', 'Electromagnetic Metamaterials',
		'Formal Hardware Verification', 'Neuromorphic Hardware',
		'Cryogenic Control Electronics'
	]::text[]),
	('mechanical-engineering', 'beginner', ARRAY[
		'Forces and Free-Body Diagrams', 'Mass and Inertia', 'Work and Mechanical Energy',
		'Mechanical Power', 'Friction', 'Simple Machines', 'Gears', 'Pulleys', 'Springs',
		'Pressure', 'Temperature', 'Heat Transfer', 'Engineering Materials',
		'Engineering Drawings', 'Measurement and Tolerances'
	]::text[]),
	('mechanical-engineering', 'intermediate', ARRAY[
		'Particle Statics', 'Rigid Body Statics', 'Trusses', 'Shear Force Diagrams',
		'Bending Moment Diagrams', 'Particle Kinematics', 'Rigid Body Kinematics',
		'Kinetics of Rigid Bodies', 'Mechanical Vibrations', 'Stress and Strain',
		'Axial Loading', 'Torsion of Shafts', 'Beam Bending', 'Column Buckling',
		'Fatigue Failure', 'Material Hardness', 'Phase Diagrams for Alloys',
		'Fluid Properties', 'Fluid Statics', 'Conservation of Mass in Fluids',
		'Bernoulli Equation', 'Internal Pipe Flow', 'External Fluid Flow',
		'First Law of Thermodynamics', 'Second Law of Thermodynamics',
		'Thermodynamic Cycles', 'Conduction Heat Transfer', 'Convection Heat Transfer',
		'Radiation Heat Transfer', 'Machine Elements', 'Rolling-Element Bearings',
		'Belt and Chain Drives', 'Welding Processes', 'Machining Processes',
		'Computer-Aided Design'
	]::text[]),
	('mechanical-engineering', 'advanced', ARRAY[
		'Continuum Mechanics', 'Elasticity Theory', 'Plasticity Theory', 'Fracture Mechanics',
		'Finite Element Analysis', 'Computational Fluid Dynamics', 'Boundary Layer Flow',
		'Compressible Flow', 'Turbomachinery', 'Gas Turbine Engineering',
		'Internal Combustion Engines', 'Refrigeration Cycles', 'Combustion Science',
		'Multiphase Flow', 'Advanced Heat Exchanger Design', 'Nonlinear Dynamics',
		'Random Vibrations', 'Rotor Dynamics', 'Acoustic Engineering',
		'Mechanical Control Systems', 'Robotic Kinematics', 'Robotic Dynamics',
		'Mechatronic Systems', 'Additive Manufacturing', 'Composite Materials',
		'Tribology', 'Reliability Engineering', 'Design Optimization',
		'Geometric Dimensioning and Tolerancing', 'Product Lifecycle Engineering'
	]::text[]),
	('mechanical-engineering', 'specialist', ARRAY[
		'Nonlinear Finite Element Methods', 'Fluid-Structure Interaction',
		'Large-Eddy Simulation', 'Direct Numerical Simulation of Turbulence',
		'Hypersonic Aerothermodynamics', 'Rarefied Gas Dynamics', 'Microfluidics',
		'Phase-Change Heat Transfer', 'Topology Optimization', 'Multiscale Materials Modeling',
		'Crystal Plasticity', 'Damage Mechanics', 'Shape Memory Alloys',
		'Magnetorheological Systems', 'Precision Machine Design',
		'Active Vibration Control', 'Soft Robotics Mechanics', 'Biomechanical Device Design',
		'Digital Twins for Mechanical Systems', 'Physics-Informed Mechanical Modeling'
	]::text[]),
	('civil-engineering', 'beginner', ARRAY[
		'Built Environment', 'Construction Materials', 'Loads on Structures',
		'Structural Foundations', 'Beams and Columns', 'Roads and Pavements', 'Bridges',
		'Water Supply Systems', 'Drainage Systems', 'Surveying', 'Topographic Maps',
		'Building Plans', 'Construction Safety', 'Sustainable Construction',
		'Infrastructure Maintenance'
	]::text[]),
	('civil-engineering', 'intermediate', ARRAY[
		'Engineering Statics', 'Structural Determinacy', 'Influence Lines',
		'Properties of Concrete', 'Reinforced Concrete Members', 'Structural Steel Members',
		'Timber Structures', 'Masonry Structures', 'Soil Classification',
		'Soil Compaction', 'Effective Stress in Soils', 'Shear Strength of Soil',
		'Shallow Foundations', 'Deep Foundations', 'Retaining Walls', 'Slope Stability',
		'Open Channel Flow', 'Pipe Network Hydraulics', 'Stormwater Management',
		'Water Treatment', 'Wastewater Treatment', 'Traffic Flow Theory',
		'Highway Geometric Design', 'Pavement Materials', 'Transportation Planning',
		'Route Surveying', 'Construction Estimating', 'Construction Scheduling',
		'Building Information Modeling', 'Contract Administration',
		'Environmental Impact Assessment', 'Flood Risk', 'Earthquake-Resistant Design',
		'Wind Loads on Buildings', 'Infrastructure Asset Management'
	]::text[]),
	('civil-engineering', 'advanced', ARRAY[
		'Structural Matrix Analysis', 'Finite Element Structural Analysis',
		'Prestressed Concrete Design', 'Composite Structural Systems',
		'Structural Dynamics', 'Seismic Structural Analysis', 'Performance-Based Seismic Design',
		'Bridge Engineering', 'Geotechnical Site Investigation',
		'Consolidation of Soils', 'Critical State Soil Mechanics',
		'Ground Improvement', 'Rock Mechanics', 'Foundation Settlement Analysis',
		'Computational Hydraulics', 'Hydrologic Modeling', 'Coastal Engineering',
		'River Engineering', 'Advanced Wastewater Processes', 'Air Pollution Control Engineering',
		'Intelligent Transportation Systems', 'Railway Engineering', 'Airport Engineering',
		'Mechanistic Pavement Design', 'Construction Risk Management',
		'Lean Construction', 'Life-Cycle Infrastructure Assessment',
		'Geospatial Engineering', 'Structural Health Monitoring', 'Urban Infrastructure Resilience'
	]::text[]),
	('civil-engineering', 'specialist', ARRAY[
		'Nonlinear Structural Analysis', 'Computational Earthquake Engineering',
		'Soil-Structure Interaction', 'Offshore Geotechnical Engineering',
		'Unsaturated Soil Mechanics', 'Geotechnical Centrifuge Modeling',
		'Probabilistic Structural Reliability', 'Blast-Resistant Structural Design',
		'Fire Engineering of Structures', 'Cable-Supported Bridge Aerodynamics',
		'Morphodynamic River Modeling', 'Urban Flood Digital Twins',
		'Coastal Sediment Transport', 'Membrane Bioreactor Engineering',
		'Advanced Oxidation Water Treatment', 'Autonomous Construction Systems',
		'Infrastructure Network Interdependency', 'Climate-Resilient Infrastructure Design',
		'Ultra-High-Performance Concrete', 'Self-Healing Construction Materials'
	]::text[]),
	('medicine', 'beginner', ARRAY[
		'Human Anatomy', 'Human Physiology', 'Cells and Tissues', 'Vital Signs',
		'Blood Components', 'Immune System', 'Infectious Diseases', 'Chronic Diseases',
		'Nutrition and Health', 'Physical Activity and Health', 'Sleep and Health',
		'Mental Health', 'Medication Safety', 'First Aid', 'Disease Prevention'
	]::text[]),
	('medicine', 'intermediate', ARRAY[
		'Medical History Taking', 'Physical Examination', 'Clinical Reasoning',
		'Diagnostic Testing', 'Complete Blood Count Interpretation', 'Electrolyte Disorders',
		'Acid-Base Disorders', 'Inflammation', 'Microbial Pathogenesis', 'Antimicrobial Therapy',
		'Pharmacokinetics', 'Pharmacodynamics', 'Adverse Drug Reactions', 'Hypertension',
		'Coronary Artery Disease', 'Heart Failure', 'Asthma',
		'Chronic Obstructive Pulmonary Disease', 'Diabetes Mellitus', 'Thyroid Disorders',
		'Acute Kidney Injury', 'Chronic Kidney Disease', 'Liver Disease',
		'Peptic Ulcer Disease', 'Anemia', 'Coagulation Disorders', 'Autoimmune Diseases',
		'Osteoporosis', 'Common Neurological Disorders', 'Mood Disorders',
		'Prenatal Care', 'Childhood Development', 'Vaccination', 'Medical Ethics',
		'Evidence-Based Medicine'
	]::text[]),
	('medicine', 'advanced', ARRAY[
		'Differential Diagnosis', 'Bayesian Clinical Reasoning', 'Electrocardiogram Interpretation',
		'Cardiac Arrhythmias', 'Valvular Heart Disease', 'Respiratory Failure',
		'Mechanical Ventilation', 'Critical Care Hemodynamics', 'Sepsis', 'Shock Syndromes',
		'Endocrine Emergencies', 'Glomerular Diseases', 'Inflammatory Bowel Disease',
		'Hematologic Malignancies', 'Solid Tumor Oncology', 'Transplant Immunology',
		'Rheumatologic Disease Management', 'Clinical Neurolocalization', 'Stroke Medicine',
		'Epilepsy Management', 'Perioperative Medicine', 'Trauma Resuscitation',
		'Maternal-Fetal Medicine', 'Neonatal Medicine', 'Pediatric Emergencies',
		'Geriatric Syndromes', 'Palliative Medicine', 'Clinical Epidemiology',
		'Randomized Clinical Trials', 'Shared Medical Decision-Making'
	]::text[]),
	('medicine', 'specialist', ARRAY[
		'Precision Oncology', 'Cancer Immunotherapy', 'Hematopoietic Stem Cell Transplantation',
		'Advanced Heart Failure Therapies', 'Structural Heart Interventions',
		'Cardiac Electrophysiology', 'Extracorporeal Membrane Oxygenation',
		'Interstitial Lung Disease', 'Pulmonary Hypertension', 'Renal Replacement Modalities',
		'Complex Hepatobiliary Disease', 'Inflammatory Neuropathology',
		'Neurocritical Care', 'Functional Neurosurgery', 'Fetal Surgery',
		'Clinical Pharmacogenomics', 'Molecular Diagnostic Pathology',
		'Rare Disease Genomics', 'Adaptive Clinical Trial Design',
		'Health Technology Assessment'
	]::text[]),
	('neuroscience', 'beginner', ARRAY[
		'Neurons', 'Glial Cells', 'Brain Anatomy', 'Spinal Cord', 'Peripheral Nerves',
		'Sensory Systems', 'Motor System', 'Reflexes', 'Neural Communication',
		'Brain Development', 'Learning and Memory', 'Emotions and the Brain', 'Sleep',
		'Brain Injury', 'Neuroplasticity'
	]::text[]),
	('neuroscience', 'intermediate', ARRAY[
		'Neuron Membrane Potential', 'Action Potentials', 'Synaptic Transmission',
		'Neurotransmitters', 'Ion Channels', 'Neural Receptors', 'Neural Circuits',
		'Central Nervous System Organization', 'Autonomic Nervous System',
		'Somatosensory Processing', 'Visual Processing', 'Auditory Processing',
		'Olfactory Processing', 'Motor Control', 'Basal Ganglia', 'Cerebellum',
		'Hypothalamic Regulation', 'Limbic System', 'Attention Networks',
		'Working Memory', 'Long-Term Memory', 'Language Networks',
		'Circadian Rhythms', 'Reward Processing', 'Stress Neurobiology',
		'Pain Pathways', 'Neuroendocrinology', 'Neuroimmune Interactions',
		'Neural Stem Cells', 'Axon Guidance', 'Synaptic Plasticity',
		'Electroencephalography', 'Functional Magnetic Resonance Imaging',
		'Neurological Examination', 'Neurodegenerative Diseases'
	]::text[]),
	('neuroscience', 'advanced', ARRAY[
		'Voltage-Gated Channel Biophysics', 'Synaptic Vesicle Cycling',
		'Long-Term Potentiation', 'Long-Term Depression', 'Homeostatic Plasticity',
		'Dendritic Computation', 'Neural Oscillations', 'Population Coding',
		'Predictive Coding', 'Decision-Making Circuits', 'Spatial Navigation Circuits',
		'Sensorimotor Integration', 'Cortical Column Organization',
		'Connectomics', 'Computational Neuroscience', 'Neural Network Modeling',
		'Brain-Computer Interfaces', 'Optogenetics', 'Chemogenetics',
		'In Vivo Calcium Imaging', 'Single-Unit Electrophysiology',
		'Deep Brain Stimulation', 'Epileptogenic Networks', 'Stroke Recovery Plasticity',
		'Alzheimer''s Disease Mechanisms', 'Parkinson''s Disease Mechanisms',
		'Neurodevelopmental Disorders', 'Addiction Neurobiology',
		'Consciousness Neuroscience', 'Social Neuroscience'
	]::text[]),
	('neuroscience', 'specialist', ARRAY[
		'Whole-Brain Circuit Reconstruction', 'Single-Cell Neural Transcriptomics',
		'Spatial Neurogenomics', 'Neural Manifold Analysis', 'Latent Neural Dynamics',
		'Closed-Loop Neural Stimulation', 'Neuromorphic Neural Interfaces',
		'Computational Psychiatry', 'Active Inference in Neural Systems',
		'Criticality in Brain Networks', 'Dendritic Plateau Potentials',
		'Tripartite Synapse Signaling', 'Myelin Plasticity', 'Glymphatic System Dynamics',
		'Blood-Brain Barrier Engineering', 'Neuroimmune Single-Cell Atlases',
		'Prion-Like Protein Propagation', 'Human Brain Organoids',
		'Comparative Connectomics', 'Neural Correlates of Metacognition'
	]::text[]),
	('psychology', 'beginner', ARRAY[
		'Human Behavior', 'Thoughts and Emotions', 'Sensation and Perception',
		'Learning', 'Memory', 'Motivation', 'Personality', 'Intelligence',
		'Human Development', 'Social Influence', 'Stress', 'Mental Well-Being',
		'Psychological Disorders', 'Psychological Therapy', 'Scientific Study of Psychology'
	]::text[]),
	('psychology', 'intermediate', ARRAY[
		'Classical Conditioning', 'Operant Conditioning', 'Observational Learning',
		'Attention', 'Working Memory', 'Long-Term Memory', 'Forgetting',
		'Problem Solving', 'Judgment and Decision-Making', 'Language and Cognition',
		'Emotion Regulation', 'Intrinsic and Extrinsic Motivation', 'Attachment Theory',
		'Cognitive Development', 'Moral Development', 'Adolescent Development',
		'Adult Development', 'Trait Theories of Personality', 'Psychometric Testing',
		'Social Cognition', 'Attitudes and Persuasion', 'Conformity and Obedience',
		'Group Dynamics', 'Interpersonal Attraction', 'Prejudice and Discrimination',
		'Altruism and Prosocial Behavior', 'Aggression', 'Health Psychology',
		'Anxiety Disorders', 'Depressive Disorders', 'Trauma-Related Disorders',
		'Cognitive Behavioral Therapy', 'Research Ethics in Psychology',
		'Correlational Research', 'Experimental Psychology'
	]::text[]),
	('psychology', 'advanced', ARRAY[
		'Signal Detection Theory', 'Psychophysics', 'Embodied Cognition',
		'Dual-Process Theories', 'Cognitive Biases', 'Metacognition',
		'Autobiographical Memory', 'Memory Reconsolidation', 'Executive Functions',
		'Theory of Mind', 'Self-Determination Theory', 'Emotional Intelligence',
		'Temperament Development', 'Person-Environment Interaction',
		'Intergroup Relations', 'Social Identity Theory', 'System Justification Theory',
		'Cultural Psychology', 'Evolutionary Psychology', 'Behavioral Genetics',
		'Psychoneuroimmunology', 'Neuropsychological Assessment',
		'Obsessive-Compulsive Disorder', 'Personality Disorders', 'Psychotic Disorders',
		'Dialectical Behavior Therapy', 'Acceptance and Commitment Therapy',
		'Multilevel Psychological Modeling', 'Longitudinal Research Design',
		'Meta-Analysis in Psychology'
	]::text[]),
	('psychology', 'specialist', ARRAY[
		'Computational Models of Cognition', 'Bayesian Models of Perception',
		'Reinforcement Learning in Decision Science', 'Ecological Momentary Assessment',
		'Experience Sampling Methodology', 'Network Models of Psychopathology',
		'Latent Growth Curve Modeling', 'Item Response Theory',
		'Measurement Invariance', 'Dynamic Structural Equation Modeling',
		'Causal Inference in Developmental Psychology', 'Cross-Cultural Psychometrics',
		'Process-Based Psychotherapy', 'Mechanisms of Exposure Therapy',
		'Transdiagnostic Models of Mental Illness', 'Predictive Processing and Psychosis',
		'Collective Memory Formation', 'Moral Judgment Neuroscience',
		'Human-Automation Trust', 'Replicability in Psychological Science'
	]::text[]),
	('history', 'beginner', ARRAY[
		'Neolithic Revolution', 'Ancient Mesopotamia', 'Ancient Egypt', 'Ancient Greece',
		'Roman Empire', 'Silk Road', 'Medieval Europe', 'Islamic Golden Age',
		'Mongol Empire', 'Renaissance', 'Protestant Reformation', 'Atlantic Slave Trade',
		'Industrial Revolution', 'First World War', 'Second World War'
	]::text[]),
	('history', 'intermediate', ARRAY[
		'Indus Valley Civilization', 'Shang and Zhou China', 'Achaemenid Persian Empire',
		'Peloponnesian War', 'Alexander the Great''s Conquests', 'Roman Republic',
		'Fall of the Western Roman Empire', 'Byzantine Empire', 'Rise of Islam',
		'Abbasid Caliphate', 'West African Sahel Empires', 'Crusades',
		'Black Death', 'Aztec Empire', 'Inca Empire', 'European Maritime Expansion',
		'Columbian Exchange', 'Scientific Revolution', 'Enlightenment',
		'American Revolution', 'French Revolution', 'Haitian Revolution',
		'Latin American Independence', 'Meiji Restoration', 'European Imperialism in Africa',
		'Opium Wars', 'Abolition of Slavery', 'National Unification of Italy and Germany',
		'Russian Revolution', 'Great Depression', 'Rise of Fascism', 'The Holocaust',
		'Decolonization', 'Cold War', 'Civil Rights Movement in the United States'
	]::text[]),
	('history', 'advanced', ARRAY[
		'Bronze Age Collapse', 'Mauryan Empire', 'Han Dynasty Statecraft',
		'Romanization of the Mediterranean', 'Late Antique Transformations',
		'Tang Dynasty Cosmopolitanism', 'Trans-Saharan Trade Networks',
		'Indian Ocean Trade System', 'Song Dynasty Commercial Revolution',
		'Ottoman Imperial Administration', 'Mughal Empire', 'Tokugawa Shogunate',
		'Thirty Years War', 'English Civil Wars', 'Qing Imperial Expansion',
		'Partition of Poland', 'Age of Atlantic Revolutions', 'Taiping Rebellion',
		'Indian Rebellion of 1857', 'Scramble for Africa', 'Armenian Genocide',
		'Collapse of the Ottoman Empire', 'Chinese Civil War', 'Partition of India',
		'Arab-Israeli Conflict', 'Cuban Revolution', 'Vietnam War',
		'Apartheid in South Africa', 'Iranian Revolution', 'Dissolution of the Soviet Union'
	]::text[]),
	('history', 'specialist', ARRAY[
		'Annales School of Historiography', 'Subaltern Studies', 'Microhistory',
		'Global History Methodology', 'Connected Histories', 'Comparative Empire Studies',
		'Environmental History', 'History of Emotions', 'Material Culture History',
		'Quantitative Historical Analysis', 'Oral History Methodology',
		'Colonial Archive Criticism', 'Historical Demography', 'Atlantic World History',
		'Borderlands History', 'Settler Colonialism', 'Transnational Labor History',
		'Memory and Commemoration', 'Genocide Historiography',
		'Digital Historical Scholarship'
	]::text[]),
	('geography', 'beginner', ARRAY[
		'Continents and Oceans', 'Latitude and Longitude', 'Map Scale', 'Cardinal Directions',
		'Time Zones', 'Landforms', 'Rivers and Watersheds', 'Climate Regions',
		'Natural Resources', 'Population Distribution', 'Cities', 'Countries and Borders',
		'Human Migration', 'Cultural Regions', 'Geographic Information'
	]::text[]),
	('geography', 'intermediate', ARRAY[
		'Topographic Maps', 'Map Projections', 'Geographic Coordinate Systems',
		'Plate Tectonic Landscapes', 'Fluvial Landscapes', 'Glacial Landscapes',
		'Arid Landscapes', 'Coastal Landscapes', 'Weather Systems',
		'Global Climate Patterns', 'Biomes', 'Soil Geography', 'Water Scarcity',
		'Population Growth', 'Demographic Transition', 'Population Pyramids',
		'Rural-to-Urban Migration', 'Refugee Movements', 'Urbanization', 'Megacities',
		'Urban Land Use', 'Economic Development', 'Global Trade Networks',
		'Agricultural Systems', 'Industrial Location', 'Tourism Geography',
		'Cultural Diffusion', 'Language Geography', 'Religious Geography',
		'Political Boundaries', 'Electoral Geography', 'Regional Inequality',
		'Globalization', 'Sustainable Cities', 'Geographic Fieldwork'
	]::text[]),
	('geography', 'advanced', ARRAY[
		'Spatial Analysis', 'Geostatistics', 'Remote Sensing',
		'Geographic Information Systems', 'Spatial Database Design',
		'Network Analysis in Geography', 'Terrain Modeling', 'Hydrological Modeling',
		'Climate Teleconnections', 'Landscape Ecology', 'Biogeography',
		'Political Ecology', 'Environmental Migration', 'Population Projection',
		'Spatial Epidemiology', 'Urban Morphology', 'Urban Segregation',
		'Housing Market Geography', 'Transport Geography', 'Logistics Networks',
		'Global Production Networks', 'Food Systems Geography',
		'Geographies of Finance', 'Critical Geopolitics', 'Territorial Sovereignty',
		'Postcolonial Geography', 'Feminist Geography', 'Health Geography',
		'Disaster Geography', 'Participatory Mapping'
	]::text[]),
	('geography', 'specialist', ARRAY[
		'Spatial Econometrics', 'Bayesian Geostatistics', 'Space-Time Point Processes',
		'Hyperspectral Remote Sensing', 'Synthetic Aperture Radar Interferometry',
		'Agent-Based Urban Modeling', 'Cellular Automata for Land-Use Change',
		'Critical Geographic Information Systems', 'Volunteered Geographic Information',
		'Mobility Data Ethics', 'Time Geography', 'Relational Economic Geography',
		'Assemblage Geographies', 'More-Than-Human Geography',
		'Decolonial Cartography', 'Indigenous Geographies', 'Carceral Geography',
		'Oceanic Geopolitics', 'Climate Security Geography', 'Planetary Urbanization'
	]::text[]),
	('philosophy', 'beginner', ARRAY[
		'Philosophical Questions', 'Arguments and Conclusions', 'Deductive Reasoning',
		'Inductive Reasoning', 'Logical Fallacies', 'Knowledge and Belief', 'Truth',
		'Personal Identity', 'Free Will', 'Moral Responsibility', 'Virtue', 'Justice',
		'Happiness and the Good Life', 'Mind and Body', 'Meaning of Life'
	]::text[]),
	('philosophy', 'intermediate', ARRAY[
		'Socratic Method', 'Plato''s Theory of Forms', 'Aristotelian Virtue Ethics',
		'Stoicism', 'Epicureanism', 'Confucian Ethics', 'Buddhist Philosophy',
		'Cartesian Doubt', 'Rationalism', 'Empiricism', 'Kantian Epistemology',
		'Skepticism', 'Correspondence Theory of Truth', 'Coherence Theory of Truth',
		'Mind-Body Dualism', 'Physicalism', 'Functionalism about Mind',
		'Consciousness', 'Compatibilism', 'Libertarian Free Will', 'Determinism',
		'Utilitarianism', 'Kantian Ethics', 'Social Contract Theory', 'Natural Law Theory',
		'Political Liberalism', 'Marxist Philosophy', 'Existentialism', 'Phenomenology',
		'Philosophy of Science', 'Problem of Induction', 'Falsifiability',
		'Philosophy of Language', 'Aesthetics', 'Environmental Ethics'
	]::text[]),
	('philosophy', 'advanced', ARRAY[
		'Modal Logic', 'Possible Worlds', 'Gettier Problem', 'Foundationalism',
		'Coherentism', 'Reliabilism', 'Social Epistemology', 'Scientific Realism',
		'Underdetermination of Theory', 'Paradigm Shifts', 'Causal Theories',
		'Personal Identity over Time', 'Intentionality', 'Qualia',
		'Extended Mind Thesis', 'Metaethics', 'Moral Realism', 'Expressivism',
		'Contractualism', 'Capabilities Approach', 'Distributive Justice',
		'Republican Freedom', 'Hermeneutics', 'Structuralism', 'Poststructuralism',
		'Pragmatism', 'Speech Act Theory', 'Reference and Meaning',
		'Philosophy of Mathematics', 'Philosophy of Technology'
	]::text[]),
	('philosophy', 'specialist', ARRAY[
		'Kripkean Modal Semantics', 'Two-Dimensional Semantics',
		'Hyperintensional Logic', 'Formal Epistemology', 'Epistemic Injustice',
		'Grounding and Metaphysical Dependence', 'Mereology', 'Metaontology',
		'Panpsychism', 'Higher-Order Theories of Consciousness',
		'Phenomenal Intentionality', 'Reasons Fundamentalism', 'Moral Particularism',
		'Constructivism in Metaethics', 'Population Ethics', 'Global Expressivism',
		'Inferential Role Semantics', 'Conceptual Engineering',
		'Social Ontology', 'Philosophy of Artificial Intelligence'
	]::text[]),
	('linguistics', 'beginner', ARRAY[
		'Human Language', 'Speech Sounds', 'Words and Morphemes', 'Sentence Structure',
		'Word Meaning', 'Language in Context', 'Language Families', 'Dialects',
		'Writing Systems', 'First Language Acquisition', 'Second Language Learning',
		'Language Change', 'Bilingualism', 'Signed Languages', 'Language Documentation'
	]::text[]),
	('linguistics', 'intermediate', ARRAY[
		'Articulatory Phonetics', 'Acoustic Phonetics', 'International Phonetic Alphabet',
		'Phonemes and Allophones', 'Syllable Structure', 'Stress and Intonation',
		'Phonological Processes', 'Inflectional Morphology', 'Derivational Morphology',
		'Morphological Typology', 'Phrase Structure', 'Syntactic Constituency',
		'Grammatical Relations', 'Case Systems', 'Agreement', 'Tense and Aspect',
		'Modality', 'Lexical Semantics', 'Semantic Roles', 'Compositional Semantics',
		'Presupposition', 'Conversational Implicature', 'Deixis', 'Speech Acts',
		'Discourse Analysis', 'Sociolinguistic Variation', 'Language and Gender',
		'Language Contact', 'Pidgins and Creoles', 'Historical Sound Change',
		'Comparative Reconstruction', 'Child Language Development',
		'Psycholinguistic Processing', 'Corpus Linguistics', 'Language Revitalization'
	]::text[]),
	('linguistics', 'advanced', ARRAY[
		'Distinctive Feature Theory', 'Optimality Theory', 'Autosegmental Phonology',
		'Laboratory Phonology', 'Distributed Morphology', 'Construction Grammar',
		'Generative Syntax', 'Dependency Grammar', 'Syntactic Movement',
		'Binding Theory', 'Information Structure', 'Formal Semantics',
		'Generalized Quantifiers', 'Event Semantics', 'Dynamic Semantics',
		'Relevance Theory', 'Conversation Analysis', 'Critical Discourse Analysis',
		'Variationist Sociolinguistics', 'Linguistic Relativity',
		'Grammaticalization', 'Language Phylogenetics', 'Neurolinguistics',
		'Eye-Tracking in Language Research', 'Computational Linguistics',
		'Statistical Language Modeling', 'Machine Translation',
		'Automatic Speech Recognition', 'Forensic Linguistics', 'Linguistic Field Methods'
	]::text[]),
	('linguistics', 'specialist', ARRAY[
		'Exemplar Models of Phonology', 'Articulatory Phonology',
		'Morphosyntactic Alignment Typology', 'Polysynthesis',
		'Minimalist Syntax', 'Head-Driven Phrase Structure Grammar',
		'Lexical Functional Grammar', 'Type-Logical Semantics',
		'Situation Semantics', 'Probabilistic Pragmatics', 'Game-Theoretic Pragmatics',
		'Interactional Sociophonetics', 'Contact-Induced Grammatical Change',
		'Bayesian Language Phylogenetics', 'Language Evolution Modeling',
		'Neural Decoding of Speech', 'Low-Resource Machine Translation',
		'Cross-Lingual Representation Learning', 'Documentary Corpus Archiving',
		'Endangered Language Reclamation'
	]::text[]),
	('literature', 'beginner', ARRAY[
		'Poetry', 'Drama', 'Fiction', 'Narrative Voice', 'Character', 'Plot', 'Setting',
		'Theme', 'Metaphor', 'Symbolism', 'Irony', 'Genre', 'Oral Tradition',
		'Literary Interpretation', 'Comparative Reading'
	]::text[]),
	('literature', 'intermediate', ARRAY[
		'Epic Poetry', 'Lyric Poetry', 'Tragedy', 'Comedy', 'The Novel', 'The Short Story',
		'The Essay', 'Unreliable Narrators', 'Point of View', 'Characterization',
		'Narrative Structure', 'Intertextuality', 'Allegory', 'Satire', 'Myth and Archetype',
		'Classical Greek Literature', 'Sanskrit Literary Traditions',
		'Classical Chinese Poetry', 'Arabic Golden Age Literature',
		'Medieval European Literature', 'Renaissance Literature', 'Romanticism',
		'Realism', 'Naturalism', 'Modernism', 'Harlem Renaissance',
		'Latin American Boom', 'Postcolonial Literature', 'Magical Realism',
		'Dystopian Literature', 'Feminist Literary Criticism', 'Historical Context in Literature',
		'Translation and Literature', 'Close Reading', 'Textual Evidence'
	]::text[]),
	('literature', 'advanced', ARRAY[
		'Narratology', 'Focalization', 'Free Indirect Discourse', 'Metafiction',
		'Stream of Consciousness', 'Dialogism', 'Polyphony in the Novel',
		'Reader-Response Criticism', 'Structuralist Literary Theory',
		'Poststructuralist Literary Theory', 'Deconstruction', 'Psychoanalytic Criticism',
		'Marxist Literary Criticism', 'Queer Literary Theory', 'Ecocriticism',
		'Critical Race Literary Theory', 'World Literature', 'Comparative Poetics',
		'Global Modernisms', 'African Oral Epics', 'Caribbean Literature',
		'Indigenous Literatures', 'Diaspora Literature', 'Prison Literature',
		'Holocaust Literature', 'Testimonio', 'Digital Literature',
		'Book History', 'Literary Canon Formation', 'Adaptation Studies'
	]::text[]),
	('literature', 'specialist', ARRAY[
		'Genetic Criticism', 'Textual Scholarship', 'Stemmatics',
		'Historical Poetics', 'Cognitive Narratology', 'Unnatural Narratology',
		'Postclassical Narratology', 'Distant Reading', 'Computational Stylistics',
		'Critical Bibliography', 'Sociology of Literary Fields',
		'Planetary Literature', 'Decolonial Literary Theory', 'Archipelagic Poetics',
		'Affect Theory in Literature', 'New Materialist Literary Criticism',
		'Vernacular Modernism', 'Translation Zone Theory',
		'Oral-Formulaic Composition', 'Manuscript Culture Studies'
	]::text[]),
	('sociology', 'beginner', ARRAY[
		'Society and Social Life', 'Culture', 'Social Norms', 'Social Roles',
		'Socialization', 'Family', 'Education', 'Religion', 'Work', 'Social Class',
		'Race and Ethnicity', 'Gender', 'Communities', 'Social Change',
		'Sociological Research'
	]::text[]),
	('sociology', 'intermediate', ARRAY[
		'Sociological Imagination', 'Functionalism', 'Conflict Theory',
		'Symbolic Interactionism', 'Social Construction of Reality', 'Institutions',
		'Bureaucracy', 'Organizations', 'Deviance', 'Social Control', 'Stratification',
		'Social Mobility', 'Poverty', 'Wealth Inequality', 'Racialization',
		'Ethnic Identity', 'Gender Socialization', 'Sexuality and Society',
		'Family Diversity', 'Sociology of Education', 'Sociology of Religion',
		'Sociology of Health', 'Labor Markets', 'Professions', 'Consumer Culture',
		'Mass Media', 'Digital Communities', 'Urban Sociology', 'Rural Sociology',
		'Migration', 'Collective Behavior', 'Social Movements', 'Demography',
		'Social Surveys', 'Participant Observation'
	]::text[]),
	('sociology', 'advanced', ARRAY[
		'Social Network Analysis', 'Cultural Capital', 'Social Capital', 'Habitus',
		'Field Theory', 'Intersectionality', 'Institutional Racism', 'Gender Performativity',
		'Life-Course Sociology', 'Generational Change', 'Comparative Welfare States',
		'Political Sociology', 'Economic Sociology', 'Sociology of Markets',
		'Global Commodity Chains', 'Precarious Labor', 'Platform Labor',
		'Carceral Sociology', 'Medicalization', 'Risk Society', 'Secularization',
		'Nationalism', 'Transnational Migration', 'Urban Segregation',
		'Gentrification', 'Environmental Sociology', 'Science and Technology Studies',
		'Digital Surveillance', 'Historical Sociology', 'Comparative-Historical Methods'
	]::text[]),
	('sociology', 'specialist', ARRAY[
		'Relational Sociology', 'Analytical Sociology', 'Mechanism-Based Explanation',
		'Multilevel Social Network Models', 'Stochastic Actor-Oriented Models',
		'Sequence Analysis of Life Courses', 'Correspondence Analysis in Cultural Sociology',
		'Computational Social Science', 'Digital Trace Data Ethics',
		'Causal Inference in Social Stratification', 'Comparative Institutional Analysis',
		'World-Systems Analysis', 'Global Historical Sociology',
		'Sociology of Quantification', 'Valuation Studies', 'Algorithmic Inequality',
		'Platform Governance', 'Epistemic Communities', 'Sociology of Expertise',
		'Public Sociology'
	]::text[]),
	('anthropology', 'beginner', ARRAY[
		'Human Cultures', 'Cultural Diversity', 'Kinship', 'Ritual', 'Religion and Belief',
		'Language and Culture', 'Subsistence', 'Exchange', 'Political Organization',
		'Human Evolution', 'Archaeological Evidence', 'Material Culture',
		'Fieldwork', 'Ethnography', 'Cultural Heritage'
	]::text[]),
	('anthropology', 'intermediate', ARRAY[
		'Cultural Relativism', 'Ethnocentrism', 'Participant Observation',
		'Ethnographic Interviews', 'Reciprocity', 'Gift Economies', 'Market Exchange',
		'Foraging Societies', 'Pastoralism', 'Agricultural Societies', 'Kinship Systems',
		'Descent and Alliance', 'Marriage Practices', 'Rites of Passage',
		'Myth and Cosmology', 'Shamanism', 'Chiefdoms', 'States and Stateless Societies',
		'Colonialism and Culture', 'Globalization and Culture', 'Medical Anthropology',
		'Economic Anthropology', 'Political Anthropology', 'Linguistic Anthropology',
		'Biological Anthropology', 'Primate Behavior', 'Hominin Evolution',
		'Human Biological Variation', 'Archaeological Dating', 'Settlement Archaeology',
		'Archaeobotany', 'Zooarchaeology', 'Museum Anthropology',
		'Indigenous Knowledge Systems', 'Applied Anthropology'
	]::text[]),
	('anthropology', 'advanced', ARRAY[
		'Symbolic Anthropology', 'Structural Anthropology', 'Interpretive Anthropology',
		'Practice Theory', 'Political Economy in Anthropology', 'Actor-Network Theory',
		'Ontological Turn', 'Multispecies Ethnography', 'Anthropology of the State',
		'Anthropology of Violence', 'Anthropology of Humanitarianism',
		'Anthropology of Infrastructure', 'Digital Anthropology',
		'Sensory Ethnography', 'Visual Anthropology', 'Ethnomusicology',
		'Language Ideologies', 'Ethnopoetics', 'Critical Medical Anthropology',
		'Biocultural Anthropology', 'Forensic Anthropology', 'Paleoanthropology',
		'Molecular Anthropology', 'Landscape Archaeology', 'Household Archaeology',
		'Experimental Archaeology', 'Archaeology of Colonialism',
		'Repatriation of Cultural Heritage', 'Community-Based Research',
		'Decolonizing Methodologies'
	]::text[]),
	('anthropology', 'specialist', ARRAY[
		'Reflexive Ethnography', 'Collaborative Ethnographic Analysis',
		'Multi-Sited Ethnography', 'Ethnography of Algorithms',
		'Infrastructure Ethnography', 'Anthropology of More-Than-Human Worlds',
		'New Kinship Studies', 'Queer Anthropology', 'Anthropology of Ethics',
		'Affect and Embodiment', 'Semiotic Anthropology', 'Linguistic Relativity Revisited',
		'Ancient Proteomics', 'Paleogenomics', 'Geometric Morphometrics',
		'Isotopic Mobility Analysis', 'Bayesian Archaeological Chronology',
		'Indigenous Archaeology', 'Critical Heritage Studies',
		'Anthropology of Planetary Crisis'
	]::text[]),
	('economics', 'beginner', ARRAY[
		'Scarcity', 'Opportunity Cost', 'Supply and Demand', 'Markets', 'Prices',
		'Competition', 'Household Budgets', 'Saving', 'Investment', 'Inflation',
		'Unemployment', 'Economic Growth', 'International Trade', 'Taxes',
		'Public Goods'
	]::text[]),
	('economics', 'intermediate', ARRAY[
		'Production Possibility Frontier', 'Comparative Advantage', 'Demand Elasticity',
		'Supply Elasticity', 'Consumer Choice', 'Utility', 'Production Costs',
		'Perfect Competition', 'Monopoly', 'Oligopoly', 'Monopolistic Competition',
		'Game Theory', 'Externalities', 'Common Resources', 'Information Asymmetry',
		'Labor Supply and Demand', 'Human Capital', 'Income Inequality',
		'Gross Domestic Product', 'Business Cycles', 'Aggregate Demand',
		'Aggregate Supply', 'Fiscal Policy', 'Monetary Policy', 'Money Creation',
		'Interest Rates', 'Exchange Rates', 'Balance of Payments', 'Trade Policy',
		'Economic Development', 'Poverty Measurement', 'Cost-Benefit Analysis',
		'Behavioral Economics', 'Economic Institutions', 'Market Failure'
	]::text[]),
	('economics', 'advanced', ARRAY[
		'General Equilibrium', 'Welfare Economics', 'Mechanism Design', 'Auction Theory',
		'Industrial Organization', 'Contract Theory', 'Principal-Agent Problems',
		'Public Choice Theory', 'Optimal Taxation', 'Economics of Education',
		'Health Economics', 'Urban Economics', 'Environmental Economics',
		'New Trade Theory', 'Economic Geography', 'Endogenous Growth Theory',
		'Real Business Cycle Theory', 'New Keynesian Economics',
		'Overlapping Generations Models', 'Consumption-Savings Models',
		'Asset Pricing Foundations', 'Central Bank Independence',
		'Currency Crises', 'Sovereign Debt', 'Development Microeconomics',
		'Randomized Policy Evaluation', 'Difference-in-Differences',
		'Regression Discontinuity', 'Instrumental Variable Estimation',
		'Economic History'
	]::text[]),
	('economics', 'specialist', ARRAY[
		'Dynamic Stochastic General Equilibrium Models', 'Heterogeneous Agent Macroeconomics',
		'Search and Matching Models', 'Incomplete Markets', 'Recursive Competitive Equilibrium',
		'Mean Field Games', 'Structural Econometrics', 'Partial Identification',
		'Synthetic Control Methods', 'Double Machine Learning for Causal Effects',
		'Optimal Transport in Economics', 'Network Formation Games',
		'Matching Market Design', 'Algorithmic Mechanism Design', 'Information Design',
		'Rational Inattention', 'Complexity Economics', 'Evolutionary Game Dynamics',
		'Climate-Economy Integrated Assessment', 'Distributional National Accounts'
	]::text[]),
	('political-science', 'beginner', ARRAY[
		'Government', 'Political Power', 'The State', 'Citizenship', 'Democracy',
		'Elections', 'Political Parties', 'Constitutions', 'Legislatures', 'Executives',
		'Courts', 'Civil Rights', 'Public Policy', 'International Relations',
		'Political Participation'
	]::text[]),
	('political-science', 'intermediate', ARRAY[
		'Sovereignty', 'Political Legitimacy', 'Separation of Powers', 'Federalism',
		'Parliamentary Government', 'Presidential Government', 'Electoral Systems',
		'Voting Behavior', 'Party Systems', 'Interest Groups', 'Social Movements',
		'Public Opinion', 'Political Communication', 'Bureaucracy', 'Policy Implementation',
		'Welfare States', 'Authoritarianism', 'Democratic Transition',
		'Political Ideologies', 'Nationalism', 'Ethnic Conflict', 'Civil-Military Relations',
		'Revolutions', 'International Organizations', 'Diplomacy', 'Balance of Power',
		'Collective Security', 'International Law', 'Human Rights Politics',
		'Foreign Policy Analysis', 'International Political Economy',
		'Development Politics', 'Comparative Political Institutions',
		'Political Research Design', 'Case Study Methods'
	]::text[]),
	('political-science', 'advanced', ARRAY[
		'Institutionalism', 'Historical Institutionalism', 'Rational Choice Institutionalism',
		'Political Culture', 'State Capacity', 'State Formation', 'Democratic Backsliding',
		'Electoral Authoritarianism', 'Coalition Formation', 'Legislative Bargaining',
		'Veto Player Theory', 'Judicial Politics', 'Public Administration',
		'Policy Feedback', 'Comparative Welfare Regimes', 'Contentious Politics',
		'Political Violence', 'Civil War Dynamics', 'Peacebuilding',
		'Nuclear Deterrence', 'Security Dilemma', 'Liberal International Order',
		'Global Governance', 'Regional Integration', 'Sanctions', 'Trade Politics',
		'Politics of Climate Change', 'Experimental Political Science',
		'Comparative Historical Analysis', 'Spatial Models of Voting'
	]::text[]),
	('political-science', 'specialist', ARRAY[
		'Formal Models of Political Institutions', 'Selectorate Theory',
		'Bayesian Models of Political Behavior', 'Ideal Point Estimation',
		'Dynamic Models of Regime Change', 'Comparative Authoritarian Institutions',
		'Autocratic Information Control', 'Constitutional Political Economy',
		'Network Analysis of Political Elites', 'Computational Political Communication',
		'Causal Mediation in Political Science', 'Synthetic Controls for Policy Evaluation',
		'Principal-Agent Models of Bureaucracy', 'International Crisis Bargaining',
		'Quantitative Conflict Forecasting', 'Nuclear Escalation Theory',
		'Global Constitutionalism', 'Transnational Advocacy Networks',
		'Polycentric Climate Governance', 'Epistemic Politics of Expertise'
	]::text[]),
	('law', 'beginner', ARRAY[
		'Rule of Law', 'Legal Rights and Duties', 'Sources of Law', 'Constitutions',
		'Legislation', 'Courts', 'Judges and Juries', 'Civil Law and Criminal Law',
		'Legal Evidence', 'Contracts', 'Property', 'Personal Injury', 'Crime and Punishment',
		'Legal Representation', 'Access to Justice'
	]::text[]),
	('law', 'intermediate', ARRAY[
		'Constitutional Separation of Powers', 'Judicial Review', 'Fundamental Rights',
		'Administrative Law', 'Statutory Interpretation', 'Legal Precedent',
		'Civil Procedure', 'Criminal Procedure', 'Burden and Standard of Proof',
		'Rules of Evidence', 'Contract Formation', 'Breach of Contract', 'Contract Remedies',
		'Tort Liability', 'Negligence', 'Strict Liability', 'Property Ownership',
		'Landlord and Tenant Law', 'Intellectual Property', 'Corporate Legal Personality',
		'Corporate Governance', 'Employment Law', 'Consumer Protection', 'Family Law',
		'Inheritance Law', 'Criminal Liability', 'Defenses to Criminal Liability',
		'Sentencing', 'International Treaties', 'State Sovereignty in International Law',
		'International Human Rights', 'Legal Ethics', 'Alternative Dispute Resolution',
		'Legal Research', 'Comparative Legal Systems'
	]::text[]),
	('law', 'advanced', ARRAY[
		'Constitutional Proportionality', 'Constitutional Originalism',
		'Constitutional Livingism', 'Administrative Deference', 'Regulatory Enforcement',
		'Class Actions', 'Complex Commercial Litigation', 'Conflict of Laws',
		'Corporate Fiduciary Duties', 'Securities Regulation', 'Competition Law',
		'Corporate Insolvency', 'International Commercial Arbitration',
		'Tax Law', 'Patent Law', 'Copyright Law', 'Trademark Law', 'Data Protection Law',
		'Cybercrime Law', 'Environmental Law', 'International Humanitarian Law',
		'International Criminal Law', 'Law of Armed Conflict', 'Refugee Law',
		'Law of the Sea', 'Treaty Interpretation', 'Transitional Justice',
		'Restorative Justice', 'Law and Economics', 'Critical Legal Studies'
	]::text[]),
	('law', 'specialist', ARRAY[
		'Constitutional Pluralism', 'Comparative Constitutional Design',
		'Emergency Powers Jurisprudence', 'Transnational Administrative Law',
		'Investor-State Dispute Settlement', 'Cross-Border Insolvency',
		'International Tax Treaty Law', 'Standard-Essential Patent Litigation',
		'Algorithmic Accountability Law', 'Artificial Intelligence Liability',
		'Platform Regulation', 'Digital Evidence Authentication',
		'Universal Jurisdiction', 'International Criminal Evidence',
		'Climate Change Litigation', 'Indigenous Legal Orders',
		'Empirical Legal Studies', 'Computational Legal Analysis',
		'Feminist Legal Theory', 'Third World Approaches to International Law'
	]::text[]),
	('art-history', 'beginner', ARRAY[
		'Cave Art', 'Ancient Egyptian Art', 'Ancient Greek Art', 'Roman Art',
		'Medieval Art', 'Renaissance Art', 'Baroque Art', 'Romantic Art', 'Realist Art',
		'Impressionism', 'Modern Art', 'Photography as Art', 'Sculpture',
		'Art Museums', 'Visual Analysis'
	]::text[]),
	('art-history', 'intermediate', ARRAY[
		'Mesopotamian Art', 'Indus Valley Art', 'Early Chinese Art', 'Buddhist Art',
		'Classical Indian Art', 'Byzantine Art', 'Islamic Art and Architecture',
		'Romanesque Art', 'Gothic Art', 'Italian Renaissance Painting',
		'Northern Renaissance Art', 'Mannerism', 'Dutch Golden Age Painting',
		'Rococo', 'Neoclassicism', 'Pre-Raphaelite Art', 'Symbolism',
		'Post-Impressionism', 'Art Nouveau', 'Expressionism', 'Cubism', 'Futurism',
		'Dada', 'Surrealism', 'Bauhaus', 'Mexican Muralism',
		'Abstract Expressionism', 'Pop Art', 'Minimalism', 'Conceptual Art',
		'West African Sculpture', 'Japanese Ukiyo-e', 'Indigenous American Art',
		'Colonial Latin American Art', 'Feminist Art'
	]::text[]),
	('art-history', 'advanced', ARRAY[
		'Iconography', 'Formalism in Art History', 'Social History of Art',
		'Psychoanalytic Art Criticism', 'Postcolonial Art History', 'Visual Culture Studies',
		'Materiality in Art', 'Patronage and Artistic Production', 'Workshop Practices',
		'Provenance Research', 'Art Conservation History', 'Museum Display Politics',
		'Looted Art and Restitution', 'Orientalism in Visual Art',
		'Atlantic World Art', 'African Modernisms', 'South Asian Modern Art',
		'Chinese Ink Painting Traditions', 'Japanese Modern Art',
		'Oceanic Art Histories', 'Indigenous Contemporary Art',
		'Harlem Renaissance Art', 'Soviet Constructivism', 'Situationist Art',
		'Performance Art', 'Land Art', 'Video Art', 'Installation Art',
		'Digital Art', 'Global Contemporary Art'
	]::text[]),
	('art-history', 'specialist', ARRAY[
		'Technical Art History', 'Pigment Provenance Analysis',
		'Dendrochronology of Panel Paintings', 'Computational Image Analysis for Art',
		'Critical Museology', 'Decolonial Curatorial Practice',
		'World Art History Methodology', 'Transcultural Art History',
		'Global Renaissance Studies', 'Mediterranean Visual Exchange',
		'Indian Ocean Art Networks', 'Black Atlantic Visual Culture',
		'Diasporic Art Histories', 'Queer Art Historiography',
		'Disability Aesthetics', 'Anthropocene Art', 'Forensic Architecture as Art Practice',
		'Algorithmic Art Histories', 'Nonhuman Agency in Art',
		'Restitution Ethics and Cultural Property'
	]::text[]),
	('music-theory', 'beginner', ARRAY[
		'Pitch', 'Rhythm', 'Meter', 'Tempo', 'Musical Dynamics', 'Timbre', 'Melody',
		'Harmony', 'Musical Texture', 'Musical Form', 'Major Scales', 'Minor Scales',
		'Intervals', 'Triads', 'Musical Notation'
	]::text[]),
	('music-theory', 'intermediate', ARRAY[
		'Key Signatures', 'Circle of Fifths', 'Diatonic Modes', 'Pentatonic Scales',
		'Chromatic Scales', 'Seventh Chords', 'Chord Inversions', 'Voice Leading',
		'Cadences', 'Harmonic Progressions', 'Non-Chord Tones', 'Secondary Dominants',
		'Modulation', 'Counterpoint', 'Motivic Development', 'Phrase Structure',
		'Binary Form', 'Ternary Form', 'Rondo Form', 'Sonata Form', 'Theme and Variations',
		'Fugue', 'Syncopation', 'Polyrhythm', 'Compound Meter', 'Orchestration',
		'Instrument Transposition', 'Lead-Sheet Symbols', 'Jazz Harmony',
		'Blues Form', 'Popular Song Form', 'Set-Class Basics', 'Ear Training',
		'Harmonic Analysis', 'Score Reading'
	]::text[]),
	('music-theory', 'advanced', ARRAY[
		'Species Counterpoint', 'Invertible Counterpoint', 'Schenkerian Analysis',
		'Neo-Riemannian Theory', 'Pitch-Class Set Theory', 'Twelve-Tone Technique',
		'Serialism', 'Atonal Voice Leading', 'Chromatic Harmony', 'Enharmonic Modulation',
		'Extended Tonality', 'Post-Tonal Form', 'Metric Dissonance',
		'Rhythmic Modulation', 'Microtonality', 'Just Intonation', 'Spectral Harmony',
		'Jazz Chord-Scale Theory', 'Bebop Harmony', 'Modal Jazz',
		'Improvisational Structure', 'Form in Popular Music', 'Film Music Analysis',
		'Electronic Music Synthesis', 'Sound Spatialization', 'Algorithmic Composition',
		'Music Cognition', 'Transformational Music Theory',
		'Corpus-Based Music Analysis', 'Performance Analysis'
	]::text[]),
	('music-theory', 'specialist', ARRAY[
		'Generalized Musical Interval Systems', 'Lewinian Transformational Networks',
		'Tonal Pitch Space', 'Mathematical Models of Voice Leading',
		'Geometric Music Theory', 'Metrical Preference Rules',
		'Temporally Emergent Meter', 'Partimento Theory', 'Schema Theory for Galant Music',
		'Historical Improvisation Practices', 'Spectromorphology',
		'Sonorous Object Theory', 'Auditory Scene Analysis in Music',
		'Computational Harmonic Inference', 'Music Information Retrieval',
		'Generative Models of Musical Structure', 'Cross-Cultural Rhythm Analysis',
		'Tuning System Temperament Theory', 'Orchestral Timbre Modeling',
		'Embodied Music Cognition'
	]::text[]),
	('architecture', 'beginner', ARRAY[
		'Architectural Space', 'Form and Function', 'Scale and Proportion', 'Building Materials',
		'Walls and Openings', 'Roofs', 'Structural Frames', 'Foundations', 'Floor Plans',
		'Building Sections', 'Facades', 'Natural Light', 'Ventilation', 'Human Scale',
		'Architectural Context'
	]::text[]),
	('architecture', 'intermediate', ARRAY[
		'Architectural Programming', 'Site Analysis', 'Circulation Design',
		'Spatial Adjacency', 'Universal Design', 'Building Codes', 'Fire Safety Design',
		'Passive Solar Design', 'Thermal Comfort', 'Daylighting', 'Building Acoustics',
		'Masonry Construction', 'Timber Construction', 'Steel Construction',
		'Reinforced Concrete Construction', 'Building Envelopes', 'Waterproofing',
		'Heating and Cooling Systems', 'Plumbing Systems', 'Electrical Building Systems',
		'Landscape Architecture', 'Urban Design', 'Vernacular Architecture',
		'Classical Architecture', 'Gothic Architecture', 'Renaissance Architecture',
		'Baroque Architecture', 'Modernist Architecture', 'Brutalist Architecture',
		'Postmodern Architecture', 'Adaptive Reuse', 'Historic Preservation',
		'Building Information Modeling', 'Architectural Visualization',
		'Design Development'
	]::text[]),
	('architecture', 'advanced', ARRAY[
		'Parametric Design', 'Computational Design', 'Generative Design',
		'Complex Geometry in Architecture', 'Long-Span Structures', 'Shell Structures',
		'Tensile Structures', 'Tall Building Design', 'Seismic Architectural Design',
		'Facade Engineering', 'High-Performance Building Envelopes',
		'Net-Zero Energy Buildings', 'Embodied Carbon in Buildings',
		'Whole-Building Life-Cycle Assessment', 'Bioclimatic Architecture',
		'Climate-Responsive Urbanism', 'Transit-Oriented Development',
		'Urban Morphology', 'Housing Typologies', 'Participatory Design',
		'Healthcare Architecture', 'Educational Architecture',
		'Industrial Architecture', 'Sacred Architecture', 'Critical Regionalism',
		'Phenomenology of Architecture', 'Architectural Semiotics',
		'Post-Occupancy Evaluation', 'Construction Coordination',
		'Integrated Project Delivery'
	]::text[]),
	('architecture', 'specialist', ARRAY[
		'Robotic Fabrication in Architecture', 'Additive Construction',
		'Discrete Architectural Assemblies', 'Topology Optimization for Structures',
		'Agent-Based Spatial Design', 'Building Performance Co-Simulation',
		'Computational Fluid Dynamics for Buildings', 'Urban Digital Twins',
		'Mass Timber High-Rise Design', 'Bio-Based Composite Structures',
		'Kinetic Building Envelopes', 'Adaptive Building Systems',
		'Climate-Adaptive Heritage Conservation', 'Post-Disaster Reconstruction',
		'Informal Settlement Upgrading', 'Space Syntax Analysis',
		'Neuroarchitecture', 'Architecture of Care', 'Decolonial Architecture',
		'Extraterrestrial Habitat Design'
	]::text[]),
	('finance', 'beginner', ARRAY[
		'Personal Budgets', 'Emergency Funds', 'Simple Interest', 'Compound Interest',
		'Bank Accounts', 'Credit and Debt', 'Loans', 'Bonds', 'Stocks', 'Investment Funds',
		'Risk and Return', 'Diversification', 'Inflation and Purchasing Power',
		'Insurance', 'Retirement Saving'
	]::text[]),
	('finance', 'intermediate', ARRAY[
		'Time Value of Money', 'Present Value', 'Future Value', 'Annuities',
		'Bond Pricing', 'Bond Yields', 'Duration', 'Equity Valuation', 'Dividend Discount Models',
		'Financial Statements', 'Financial Ratio Analysis', 'Cash Flow Analysis',
		'Capital Budgeting', 'Net Present Value', 'Internal Rate of Return',
		'Cost of Capital', 'Capital Structure', 'Working Capital Management',
		'Portfolio Theory', 'Systematic and Unsystematic Risk',
		'Capital Asset Pricing Model', 'Index Investing', 'Exchange-Traded Funds',
		'Mutual Funds', 'Foreign Exchange Markets', 'Futures Contracts', 'Options Contracts',
		'Hedging', 'Credit Risk', 'Market Risk', 'Liquidity Risk', 'Corporate Governance',
		'Behavioral Finance', 'Financial Regulation', 'Tax-Efficient Investing'
	]::text[]),
	('finance', 'advanced', ARRAY[
		'Discounted Cash Flow Valuation', 'Relative Valuation', 'Leveraged Buyouts',
		'Mergers and Acquisitions', 'Initial Public Offerings', 'Private Equity',
		'Venture Capital', 'Structured Finance', 'Securitization',
		'Interest Rate Term Structure', 'Fixed-Income Immunization',
		'Credit Derivatives', 'Option Pricing', 'Black-Scholes Model',
		'Binomial Option Models', 'Options Greeks', 'Volatility Surfaces',
		'Value at Risk', 'Expected Shortfall', 'Stress Testing', 'Asset-Liability Management',
		'Factor Investing', 'Arbitrage Pricing Theory', 'Performance Attribution',
		'International Portfolio Management', 'Commodity Finance',
		'Real Estate Finance', 'Project Finance', 'Sustainable Finance',
		'Financial Econometrics'
	]::text[]),
	('finance', 'specialist', ARRAY[
		'Stochastic Calculus for Finance', 'Risk-Neutral Valuation',
		'Martingale Pricing Theory', 'Stochastic Volatility Models',
		'Local Volatility Models', 'Interest Rate Short-Rate Models',
		'Heath-Jarrow-Morton Framework', 'Credit Intensity Models',
		'Counterparty Credit Valuation Adjustment', 'X-Value Adjustments',
		'Collateral Optimization', 'Algorithmic Market Making',
		'High-Frequency Market Microstructure', 'Optimal Trade Execution',
		'Quantitative Portfolio Construction', 'Robust Portfolio Optimization',
		'Alternative Risk Premia', 'Systemic Risk Networks',
		'Climate Financial Risk Modeling', 'Decentralized Finance Protocol Risk'
	]::text[])
), expanded AS (
	SELECT subject_slug, level, unnest(names) AS name
	FROM catalog
)
INSERT INTO "knowledge_topics" ("subject_slug", "slug", "name", "level")
SELECT
	subject_slug,
	trim(BOTH '-' FROM regexp_replace(lower(replace(name, '''', '')), '[^a-z0-9]+', '-', 'g')),
	name,
	level
FROM expanded;
